### ISSUE TITLE
Plasma crash when applet is active

### ISSUE THREAD

**Issue by swiatlyk** [psifidotos/applet-window-buttons#101]
I'm having big problem with KDE Neon and applet. When I want to maximize window or edit panel where applet is placed my whole plasma crashes, only black screen shows and I can't do anything. Only ctrl+alt+delete and then logout and login helps to see plasma again.
Also When I added applet to desktop, then after desktop is loaded, plasma crashes immediately. 
Occurs always when I want to maximize window or edit panel or when Plasma try's to load applet.
Solution: uninstall applet and remowe `BorderlessMaximizedWindows=true` from kwinrc file.
Applet was installed via sudo add-apt-repository ppa:krisives/applet-window-buttons
sudo apt install applet-window-buttons
Link to version: https://launchpad.net/~krisives/+archive/ubuntu/applet-window-buttons/+index?field.series_filter=
KDE information:
Plasma version: 5.18.5
Plasma framework: 5.70.0
QT version: 5.14.2
Kernel version: 5.3.0-53

**Comment by psifidotos** [comment]
Crashes from the applet have two main reasons:

1. Applet is not built correctly with the same kdecoration library that your plasma system is using
2. The window decoration you are using creates the crash, try to use Breeze decoration buttons to confirm this is the case.

**Comment by psifidotos** [comment]
So both 1,2 are downstream issues and the not of this applet fault.
