### ISSUE TITLE
Blacklist for windows enforcing CSD

### ISSUE THREAD

**Issue by alxlg** [psifidotos/applet-window-buttons#102]
Some applications enforce the use of Client-Side Decorations i.e. they draw window controls on their own, resulting in a duplication with this applet.

I think it would be nice to have in this applet settings the ability to define a blacklist of window classes (like KWin Rules): when a window in the blacklist is focused the applet wouldn't show the controls.

Does make sense?

**Comment by psifidotos** [comment]
this falls to per app responsibility just like firefox and telegram are now providing

**Comment by alxlg** [comment]
Of course, though GNOME(-ish) apps all use CSD only and more and more new Linux apps are providing just CSD. I filled bug reports to many of them asking for optional SSD support but no one cares.
