### ISSUE TITLE
Split screen?

### ISSUE THREAD

**Issue by SmartBoy84** [psifidotos/applet-window-buttons#105]
When I do splitscreen, the applet doesn't recognise the window as being maximised even though it is behind the applet.
Could I ask that you have an option which trigger the appearance of the applet when the current window is behind the applet (can you use some form of hook/trigger from latte-dock).

![image](https://user-images.githubusercontent.com/12468102/91533630-c32f6d00-e942-11ea-9db2-7ece94d72459.png)

I understand that this doesn't impact most normal setups but in my case is does have an influence and can be a great annoyance sometimes.

[edit] I am using latte-dock and it is able to recognise when it is covering a window.
I am using this pre-made setup: https://www.reddit.com/r/kde/comments/g7w11z/moe_moe_dark_themes/

**Comment by psifidotos** [comment]
this is out of scope
