### ISSUE TITLE
[Feature Request] Add option to ignore some windows

### ISSUE THREAD

**Issue by mateushonorato** [psifidotos/applet-window-buttons#108]
Since some apps have window buttons built-in inside them, like WPS office, and doesn't give us the option to hide them, would be nice to have the option to ignore those windows (maybe by the title or anything) and don't show buttons for them. Is this possible somehow?

**Comment by Sadi58** [comment]
This is true for Vivaldi web browser, too.

**Comment by psifidotos** [comment]
Sorry I dont like the idea and also it is a mess to implement.

**Comment by Sadi58** [comment]
If this is kind of complicated to do in window buttons applet,
then we should better ask the developers of those apps to fix this
as it's actually their fault that their maximized window is not behaving like others.
