### ISSUE TITLE
Disable borders for maximizerd windows seems to not work for gtk app (eg: pacman).

### ISSUE THREAD

**Issue by laltroweb** [psifidotos/applet-window-buttons#109]
Hi, this settings work for most apps (chrome, gimp, thunderbird, dolphin, etc ... but seems to not work for some app like gnome disk and pacman. is there something i can do for fix? thanks :+1: 
![Screenshot_20201205_154508](https://user-images.githubusercontent.com/16841896/101246030-fab36f80-3710-11eb-8a49-d7da545d6217.png)

**Comment by psifidotos** [comment]
Gtk when using Client Side Decorations does not support this
