### ISSUE TITLE
Arc window buttons don't work

### ISSUE THREAD

**Issue by Sadi58** [psifidotos/applet-window-buttons#110]
When I selected Arc buttons, I could see the buttons in the applet configuration window, but the panel was blank. Also, when I had a maximized window, clicking anywhere in that blank space was ineffective. Next time, when I chose other buttons, and returned to Arc, the applet displayed the last working buttons instead of the chosen Arc (very smart move). I don't know if this is caused by the Arc theme itself and should be reported there though...

**Comment by psifidotos** [comment]
What is the theme exactly for which the applet does not paint its buttons? Provise its link please.

**Comment by Sadi58** [comment]
I cannot reproduce this issue now; probably something has fixed it since then, or it was a one-off odd behavior.
