### ISSUE TITLE
Compilation error on Plasma 5.21 

### ISSUE THREAD

**Issue by dr460nf1r3** [psifidotos/applet-window-buttons#113]
Hey, after upgrading to plasma-git on Arch Linux the applet does not work anymore showing this: 
`Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: plugin cannot be loaded for module "org.kde.appletdecoration": Cannot load library /usr/lib/qt/qml/org/kde/appletdecoration/libappletdecorationplugin.so: (libkdecorations2private.so.7: cannot open shared object file: No such file or directory)
`
Of course this is probably caused by upgrading to newer KF5 so I tried recompiling against the newer libraries but that errors out, log can be found [here](https://bin.garudalinux.org/?af53762abc32e2fc#4c1vtEtNqTZ2Rux81StBGkqwDkFGbrwBByb3mFKUSBJZ). 

And btw, thanks for these great applets. They bring Plasma to another level of beauty! :)

**Comment by psifidotos** [comment]
The error points to kdecoration2 library missing, it could be a distro issue.

**Comment by andrevmatos** [comment]
With plasma 5.21beta, the so file got bumped to `libkdecorations2private.so.8`. I'm getting this error here as well trying to load the current version with latest plasma beta.

**Comment by psifidotos** [comment]
Ok, so with plasma 5.21 kdecoration2 changed a header.

**Comment by psifidotos** [comment]
Show me please your compilation output

**Comment by dr460nf1r3** [comment]
[Here](https://bin.garudalinux.org/?d8c7f8a9daea93ea#Az3n9PPFiaDaFJMnmfPqciBvYQq8bsg528pop4sTiuc5) you are.
