### ISSUE TITLE
Button Size in All Aurorae Themes Except Breeze / Breeze-blurred Have Size Option Greyed Out

### ISSUE THREAD

**Issue by BigBossAnwer** [psifidotos/applet-window-buttons#116]
Issue encountered after updating to Plasma 5.21:
All Aurorae window button themes except the default Breeze / Breeze-Blurred do not allow for percentage button scaling in the widget configuration menu.
I am able to alter the button size on non-Breeze Aurorae themes by changing the system wide button size in the Plasma Config Menu, but this creates comically over sized buttons in normal windows just to have appropriately sized buttons in the panel widget.

Any help or direction on this issue would be appreciated.

**Comment by psifidotos** [comment]
have you disabled option "Metrics: Use from decoration if any are found"?

**Comment by BigBossAnwer** [comment]
Well now I feel quite dumb. Unchecking the "use metrics from decoration" option resolved the issue.
Thank you for the incredibly quick reply.
