### ISSUE TITLE
[Bug Report]  Can not load

### ISSUE THREAD

**Issue by BlueQuantumx** [psifidotos/applet-window-buttons#117]
When I update to the latest version of Plasma 5.21.0, it can't work.

![image](https://user-images.githubusercontent.com/78394824/108837274-f3fc1080-760c-11eb-8e4a-6d547c0f1eda.png)

### Here is the detail:

> file:///usr/share/plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: plugin cannot be loaded for module "org.kde.appletdecoration": Cannot load library /usr/lib/qt/qml/org/kde/appletdecoration/libappletdecorationplugin.so: (libkdecorations2private.so.7: cannot open shared object file: No such file or directory)

**Comment by psifidotos** [comment]
use latest master and reinstall
