### ISSUE TITLE
window cannot unmaximize normally

### ISSUE THREAD

**Issue by arxim-lab** [psifidotos/applet-window-buttons#118]
![Peek 2021-02-25 23-44](https://user-images.githubusercontent.com/7345998/109178374-c0afb200-77c3-11eb-9fb8-1dba7fe6f101.gif)
just like this

**Comment by psifidotos** [comment]
What are you showing in the video? The video is not showing your full desktop.

**Comment by arxim-lab** [comment]
https://user-images.githubusercontent.com/7345998/109262838-32781200-783d-11eb-84e2-708eaa853cd6.mp4

**Comment by arxim-lab** [comment]
Oh sorry, there was something wrong with dolphin, and i have fixed this.
