### ISSUE TITLE
(IMPORTANT) KDE Update has seemingly broken the widget.

### ISSUE THREAD

**Issue by phoenix277yt** [psifidotos/applet-window-buttons#119]
TL;DR - Manjaro had kde 5.21 update, window-title and window-appmenu are fine but window-buttons has been broken. it is displayed but no buttons and nothing in "General" part of the plasmoid menu. will provide more details tomorrow.

**Comment by phoenix277yt** [comment]
I am gonna try switching to the latest release (am on jan 23 one) tomorrow but still.

**Comment by psifidotos** [comment]
update to latest master version
