### ISSUE TITLE
Keep activated when a window is fullscreen to avoid 'jumping'

### ISSUE THREAD

**Issue by sanderboom** [psifidotos/applet-window-buttons#12]
First of all: thanks for all the great stuff you are doing for Plasma desktop!

Second: I like this plasmoid a lot, and have it set to 'Show only when active window is maximized'. I also have yakuake set to always go fullscreen via: 

<img width="485" alt="image" src="https://user-images.githubusercontent.com/5956570/48266688-65115d00-e430-11e8-8aa7-ba0ed75174ea.png">

Apparently the buttons also hide when the active window is fullscreen, so every time yakuake loses focus and closes, the buttons jump into place (b/c I most of the time have a fullscreen window open...). Anyhow, is it possible to keep showing the buttons when the active application is fullscreen? Or maybe via a setting?

Thanks for looking into this!

**Comment by psifidotos** [comment]
When a window is fullscreen this applet should not be shown.
Do I miss something?

**Comment by psifidotos** [comment]
nope... this is panels and docks responsibility and it is a breakage of API
