### ISSUE TITLE
Not working on Plasma 5.21

### ISSUE THREAD

**Issue by NovaViper** [psifidotos/applet-window-buttons#120]
Hi, after updating to Plasma 5.21, I getting this error

```
file:///usr/share/plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: plugin cannot be loaded for module "org.kde.appletdecoration": Cannot load library /usr/lib/qt/qml/org/kde/appletdecoration/libappletdecorationplugin.so: (libkdecorations2private.so.7: cannot open shared object file: No such file or directory)
```
I'm using the [AUR for the applet](http://aur.archlinux.org/packages/plasma5-applets-window-buttons-git), with git build 1668c69

System Info
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.18-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by psifidotos** [comment]
You latest master version

**Comment by psifidotos** [comment]
You need latest master version

**Comment by NovaViper** [comment]
> You need latest master version

THat's the version im using, 16c66e9 is the latest commit from the master branch

**Comment by NovaViper** [comment]
Ah I see! I had 1668c69, not 16c66e9
