### ISSUE TITLE
Close button does not work when the cursor is on the right border

### ISSUE THREAD

**Issue by a1d4r** [psifidotos/applet-window-buttons#121]
The close button is active but does not work. It happens while hovering the mouse pointer right on the right border (including top right corner). Video: https://youtu.be/dzRcAE3H0JU

Both left and right margins are set to 0px.

Windows Buttons Applet 0.8.1
KDE Plasma 5.21.1

**Comment by krikoCodeCook** [comment]
I can confirm the same issue on my machine. It started to happen after upgrading to KDE Plasma 5.21.

**Comment by psifidotos** [comment]
1. Have you tested with master version?
2. Are you using Latte or plasma panel?

**Comment by krikoCodeCook** [comment]
1. I've just tested with the master version, same behaviour
2. I'm using the widget inside of plasma panel

**Comment by psifidotos** [comment]
Please report it to plasmashell at: https://bugs.kde.org/enter_bug.cgi?product=lattedock
this is not only window buttons related, add instead of the window buttons an application launcher at the most right position of the panel, you will see that same problem appears.

UPSTREAM

**Comment by psifidotos** [comment]
https://bugs.kde.org/enter_bug.cgi?product=plasmashell

**Comment by a1d4r** [comment]
1. Yes, it happens with master version
2. I'm using Latte Dock but it is located at the bottom of the screen. 

I've just tested the most right position with an application launcher, it works as expected. Here is a video: https://youtu.be/52gEWDo_Muw

**Comment by psifidotos** [comment]
Because two different people aren't describing different issues probably.

@a1d4r describe in one sentence your problem with details please.

**Comment by psifidotos** [comment]
and that is the proof, 2px gap on the right side: 

![εικόνα](https://user-images.githubusercontent.com/2216474/110924849-30c54880-832b-11eb-93d1-9dae8249e149.png)

**Comment by psifidotos** [comment]
I added the bug report for you, you can follow it at: https://bugs.kde.org/show_bug.cgi?id=434315

**Comment by a1d4r** [comment]
> Because two different people aren't describing different issues probably.
> 
> @a1d4r describe in one sentence your problem with details please.

The problem is already described in the title. I see a bug report, thanks. 

My previous message was a reply to your statement: "this is not only window buttons related, add instead of the window buttons an application launcher at the most right position of the panel, you will see that same problem appears." 

That's not true for me, I switched "window buttons applet" with "application launcher". With the application launcher there is no such problem at the most right position. I recorded the video: https://www.youtube.com/watch?v=52gEWDo_Muw

**Comment by psifidotos** [comment]
The two different issues are:

A. At the right most part the close button does not work but when someone clicks inside the close button the window closes

B. When someone clicks the close button the window does not close

A is a plasma panel bug and responsibility to fix, personally I use latte panels and I am fine. I dont know why your application launcher works in my system even the systray doea not pop up. Plasma panels in 5.21 have updated their padding mechanism so they can have bugs.

B. Is not related to A my guess is that the specific window that is not closing is defining that it is not Closable, it could be a client side decorated window or something else... No idea, in any case as the window defines that it is not clozable the window buttons wont close it.
