### ISSUE TITLE
Buttons display with gtk window decorations

### ISSUE THREAD

**Issue by UltraBlackLinux** [psifidotos/applet-window-buttons#129]
Hey there,
There is this "Bug", where the window buttons show, even though the window has them integrated, for example with gtk apps, here a screenshot:

![Screenshot_5](https://user-images.githubusercontent.com/62404294/119704044-79cf6800-be57-11eb-952e-5918f9316e50.png)

Please add an option to hide the buttons, when gtk apps are used.
Thanks!

**Comment by psifidotos** [comment]
This is no bug from the applet. Real solution is for Gtk to provide a user option to disable client side windows for maximized windows.

So this is upstream.

**Comment by misketmuskat** [comment]
So there is no solution for this?

How about adding "disabling applet to show on selected applications" as an option? That way we can select applications like firefox and pamac-manager from applet's settings, so there will be no doubling of window buttons?
