### ISSUE TITLE
Disable Borders for Maximized Windows will fail after the computer restarts

### ISSUE THREAD

**Issue by KingSingleDog** [psifidotos/applet-window-buttons#133]
Every time I rebooted my computer I had to turn off the Disable Borders for Maximized function in Windows Buttons Settings again (even though it was already on) for it to take effect. Is this my configuration wrong?

**Comment by KingSingleDog** [comment]
After a restart, the Disable Borders for Maximized Windows feature appears to be on, but it does not work. So EVERY time I have to turn it off and on again for it to work properly.

**Comment by rodrigo426** [comment]
Are you using Latte Dock?

If yes you need to go to 'Configure Latte > Preferences' and enable 'Support borderless maximized windows in different layouts' then enable the 'Borderless' option on your Latte Layout under 'Configure Latte > Layouts Editor'.

[Latte-Dock wiki's topic regarding borderless maximized windows](https://github.com/psifidotos/Latte-Dock/wiki/Tips-&-Tricks#q-can-i-have-different-borderlessmaximized-windows-option-between-different-layouts) 

I hope it works for you.

**Comment by KingSingleDog** [comment]
hoo! it work for me, thank you so much😺😺😺

**Comment by KingSingleDog** [comment]
@rodrigo426 hoo! it work for me, thank you so much 😺  😺  😺
