### ISSUE TITLE
The buttons are shown on startup

### ISSUE THREAD

**Issue by sccoouut** [psifidotos/applet-window-buttons#136]
The applet's buttons are shown on startup, even when any window is not shown or present, although the window title (also from yours applet) is not. It is shown until I click on any key.
My "Show"-option is "Active window is present'.

Steps to reproduce:
1. Put applet to latte-dock panel.
2. Enable latte-dock autostart.
3. Reboot your system.

Screenshot:
![image](https://user-images.githubusercontent.com/88430645/131038012-717442e9-f611-4af3-975a-d4a7c11160c5.png)

UPD:
Also I have noticed that the buttons are shown only when startup-notifications (like "Wired connection enabled") are shown.

**Comment by felagund** [comment]
Also they are shown when all windows on the given monitor are minimized (and also when all windows on all monitors are minimized). I think this should not - not sure if it is the same issue, I can open a new one.

**Comment by psifidotos** [comment]
The startup issue is not reproducable or it isnt that prominent in my system. 

The second issue I can not understand what you are referring at, please open a new bug report and report also the applet version and the latte version.

You may be too outdated.

**Comment by felagund** [comment]
Sorry, I commented here before going tothe options, now it works as intended. I deleted my comment in the hope it would not reach anywhere but it apparently did. Just ignore it.
