### ISSUE TITLE
Last active window is maximized dont work

### ISSUE THREAD

**Issue by agent188** [psifidotos/applet-window-buttons#137]
1. Set show status "Last active window is maximized"
2. Minimizing the window
3. Maximized the window
4. Result
KDE Version: 5.22.4
KDE Frameworks: 5.85.0
Qt version: 5.15.2

**Comment by psifidotos** [comment]
Are you using plasma or latte panel?

**Comment by psifidotos** [comment]
works just fine with Latte v0.10.1

**Comment by agent188** [comment]
> Are you using plasma or latte panel?

Latte panel

**Comment by agent188** [comment]
My version lattedock 0.10.0 lol

**Comment by psifidotos** [comment]
works perfectly fine with master version of the applet. are you sure the steps to reproduce are the ones you provided?

**Comment by psifidotos** [comment]
actually what is the problem? what is the problem you are describing?

**Comment by agent188** [comment]
![изображение](https://user-images.githubusercontent.com/41228098/131455242-42397bdc-8f7f-4576-8534-d69b3a6e3ce8.png)
Buttons in window dont hidden when window is maximazed

**Comment by agent188** [comment]
the hide animation also doesn't work

**Comment by agent188** [comment]
I apologize for the inaccuracy

**Comment by agent188** [comment]
I found solution in https://github.com/psifidotos/applet-window-buttons/issues/133
