### ISSUE TITLE
[Feature Request] Colors from latte

### ISSUE THREAD

**Issue by Leplik500** [psifidotos/applet-window-buttons#138]
I would like to color buttons according to latte colors pallete(dark or light). It should work at least with black-and-white auroraes. 
![image](https://user-images.githubusercontent.com/51443060/134176471-59a51c9d-b988-4221-8ecd-2e5d76ab232b.png)

**Comment by psifidotos** [comment]
it is already provided you need to update your aurorae theme rc file, https://github.com/psifidotos/applet-window-buttons/issues/111
