### ISSUE TITLE
Add exceptions for windows with their own decorations

### ISSUE THREAD

**Issue by csolisr** [psifidotos/applet-window-buttons#141]
There are a few applications that the applet doesn't correctly recognize as having their own windows decorations apart from KWin, and this causes the applet to show duplicate sets of buttons:

- Web browsers that allow hiding the system's window bar and show their own minimize/maximize/close buttons instead (such as Firefox and Chrome)
- Applications that bypass the window decoration manager entirely (such as Steam)
- Applications built with GNOME's Client Side Decorations (CSD), that also bypass the window decoration manager

For this kind of cases, I would like to have an option to either skip showing the buttons on the widget to prevent duplicates, or (if it's within the scope of this project) an option to hide the buttons on the custom client-side decorations. At least I'm aware that [GNOME Shell's "Window Buttons Extension"](https://github.com/danielkza/Gnome-Shell-Window-Buttons-Extension) is able to detect the GNOME CSD and hide the buttons while CSD apps are maximized.

**Comment by psifidotos** [comment]
not interested, gtk should fine a way to solve this

**Comment by Fosssil** [comment]
please
