### ISSUE TITLE
could not build and install in kde plasma version 5.23

### ISSUE THREAD

**Issue by subhkr19** [psifidotos/applet-window-buttons#143]
I have tried to build and install on the latest KDE plasma version 5.23 and I had some errors.
here the results:

install.sh: 1: [: -a: unexpected operator
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:18 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.87.0") 
Installing in /usr. Run /home/subh/Downloads/widgets/applet-window-buttons-master/build/prefix.sh to set the environment for applet_windowbuttons.
-- Found KF5Declarative: /usr/lib/x86_64-linux-gnu/cmake/KF5Declarative/KF5DeclarativeConfig.cmake (found version "5.87.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found KF5Plasma: /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.87.0") 
-- Found KF5PlasmaQuick: /usr/lib/x86_64-linux-gnu/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.87.0") 
-- Found KF5: success (found suitable version "5.87.0", minimum required is "5.38.0") found components: CoreAddons Declarative Plasma PlasmaQuick 
fatal: not a git repository (or any of the parent directories): .git
Installing in /usr. Run /home/subh/Downloads/widgets/applet-window-buttons-master/build/prefix.sh to set the environment for applet_windowbuttons.
-- KDECORATION2 VERSION MINOR : 23
Installing in /usr. Run /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/prefix.sh to set the environment for applet_windowbuttons.
-- Could not set up the appstream test. appstreamcli is missing.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  libappletdecoration/CMakeLists.txt:37 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.87.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.87.0") 
-- Found KF5Service: /usr/lib/x86_64-linux-gnu/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.87.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.87.0") 
-- Found KF5: success (found suitable version "5.87.0", minimum required is "5.26.0") found components: Plasma WindowSystem I18n Service ConfigWidgets 
-- Configuring done
CMake Warning at libappletdecoration/CMakeLists.txt:34 (add_library):
  Cannot generate a safe runtime search path for target
  appletdecorationplugin because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libQt5Widgets.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/subh/anaconda3/lib
    runtime library [libQt5Xml.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/subh/anaconda3/lib
    runtime library [libQt5DBus.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/subh/anaconda3/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/subh/Downloads/widgets/applet-window-buttons-master/build
Scanning dependencies of target org.kde.windowbuttons-plasmoids-metadata-json
Scanning dependencies of target appletdecorationplugin_autogen
[  9%] Generating org.kde.windowbuttons-plasmoids-metadata.json
[  9%] Automatic MOC for target appletdecorationplugin
About to parse service type file "/usr/share/kservicetypes5/plasma-applet.desktop"
Found property definition "X-Plasma-API" with type "QString"
Found property definition "X-Plasma-RootPath" with type "QString"
Found property definition "X-Plasma-MainScript" with type "QString"
Found property definition "X-Plasma-ContainmentType" with type "QString"
Found property definition "X-Plasma-DropMimeTypes" with type "QStringList"
Found property definition "X-Plasma-DropUrlPatterns" with type "QStringList"
Found property definition "X-Plasma-NotificationArea" with type "QString"
Found property definition "X-Plasma-NotificationAreaCategory" with type "QString"
Found property definition "X-Plasma-DBusActivationService" with type "QString"
Found property definition "X-KDE-ParentApp" with type "QString"
Found property definition "X-Plasma-Provides" with type "QStringList"
Found property definition "X-Plasma-PreloadWeight" with type "int"
Found property definition "X-Plasma-ConfigPlugins" with type "QStringList"
Found property definition "X-Plasma-StandAloneApp" with type "bool"
Found property definition "X-Plasma-RequiredExtensions" with type "QStringList"
Found property definition "NoDisplay" with type "bool"
Unknown property type for key "Keywords" -> falling back to string
Generated  "/home/subh/Downloads/widgets/applet-window-buttons-master/build/org.kde.windowbuttons-plasmoids-metadata.json"
[  9%] Built target org.kde.windowbuttons-plasmoids-metadata-json
[  9%] Built target appletdecorationplugin_autogen
Scanning dependencies of target appletdecorationplugin
[ 13%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o
[ 18%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o
[ 22%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/auroraetheme.cpp.o
[ 27%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/buttonsmodel.cpp.o
In file included from /home/subh/anaconda3/include/qt/QtCore/qnamespace.h:43,
                 from /home/subh/anaconda3/include/qt/QtCore/qobjectdefs.h:48,
                 from /home/subh/anaconda3/include/qt/QtCore/qobject.h:46,
                 from /home/subh/anaconda3/include/qt/QtCore/QObject:1,
                 from /usr/include/KDecoration2/kdecoration2/decorationbutton.h:12,
                 from /usr/include/KDecoration2/KDecoration2/DecorationButton:1,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/buttonsmodel.h:27,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/buttonsmodel.cpp:24:
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KLocalizedContextPrivate>; typename Wrapper::pointer = KLocalizedContextPrivate*]’:
/usr/include/KF5/KI18n/klocalizedcontext.h:279:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KLocalizedContextPrivate>’ has no member named ‘data’
  999 | template <typename Wrapper> static inline typename Wrapper::pointer qGetPtrHelper(const Wrapper &p) { return p.data(); }
      |                                                                                                              ~~^~~~
In file included from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/appletdecorationplugin.cpp:26:
/home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/previewbridge.h:53:10: error: ‘void Decoration::Applet::PreviewBridge::update(KDecoration2::Decoration*, const QRect&)’ marked ‘override’, but does not override
   53 |     void update(KDecoration2::Decoration *decoration, const QRect &geometry) override;
      |          ^~~~~~
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:102: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/buttonsmodel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/subh/anaconda3/include/qt/QtGui/qtguiglobal.h:43,
                 from /home/subh/anaconda3/include/qt/QtGui/qcolor.h:43,
                 from /home/subh/anaconda3/include/qt/QtGui/QColor:1,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/auroraetheme.h:23,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/auroraetheme.cpp:20:
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginFactoryPrivate>; typename Wrapper::pointer = KPluginFactoryPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginfactory.h:408:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginFactoryPrivate>’ has no member named ‘data’
  999 | template <typename Wrapper> static inline typename Wrapper::pointer qGetPtrHelper(const Wrapper &p) { return p.data(); }
      |                                                                                                              ~~^~~~
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginLoaderPrivate>; typename Wrapper::pointer = KPluginLoaderPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginloader.h:422:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginLoaderPrivate>’ has no member named ‘data’
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KSycocaEntryPrivate>; typename Wrapper::pointer = KSycocaEntryPrivate*]’:
/usr/include/KF5/KService/ksycocaentry.h:139:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KSycocaEntryPrivate>’ has no member named ‘data’
In file included from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/moc_previewbridge.cpp:9,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/mocs_compilation.cpp:9:
/home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/previewbridge.h:53:10: error: ‘void Decoration::Applet::PreviewBridge::update(KDecoration2::Decoration*, const QRect&)’ marked ‘override’, but does not override
   53 |     void update(KDecoration2::Decoration *decoration, const QRect &geometry) override;
      |          ^~~~~~
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:89: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/auroraetheme.cpp.o] Error 1
In file included from /home/subh/anaconda3/include/qt/QtCore/qnamespace.h:43,
                 from /home/subh/anaconda3/include/qt/QtCore/qobjectdefs.h:48,
                 from /home/subh/anaconda3/include/qt/QtCore/qobject.h:46,
                 from /home/subh/anaconda3/include/qt/QtCore/qplugin.h:43,
                 from /home/subh/anaconda3/include/qt/QtQml/qqmlextensionplugin.h:43,
                 from /home/subh/anaconda3/include/qt/QtQml/QQmlExtensionPlugin:1,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/appletdecorationplugin.h:23,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/moc_appletdecorationplugin.cpp:9,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/mocs_compilation.cpp:2:
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginFactoryPrivate>; typename Wrapper::pointer = KPluginFactoryPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginfactory.h:408:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginFactoryPrivate>’ has no member named ‘data’
  999 | ypename Wrapper> static inline typename Wrapper::pointer qGetPtrHelper(const Wrapper &p) { return p.data(); }
      |                                                                                                   ~~^~~~

/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginLoaderPrivate>; typename Wrapper::pointer = KPluginLoaderPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginloader.h:422:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginLoaderPrivate>’ has no member named ‘data’
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KSycocaEntryPrivate>; typename Wrapper::pointer = KSycocaEntryPrivate*]’:
/usr/include/KF5/KService/ksycocaentry.h:139:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KSycocaEntryPrivate>’ has no member named ‘data’
In file included from /home/subh/anaconda3/include/qt/QtCore/qnamespace.h:43,
                 from /home/subh/anaconda3/include/qt/QtCore/qobjectdefs.h:48,
                 from /home/subh/anaconda3/include/qt/QtCore/qobject.h:46,
                 from /home/subh/anaconda3/include/qt/QtCore/qplugin.h:43,
                 from /home/subh/anaconda3/include/qt/QtQml/qqmlextensionplugin.h:43,
                 from /home/subh/anaconda3/include/qt/QtQml/QQmlExtensionPlugin:1,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/appletdecorationplugin.h:23,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/appletdecorationplugin.cpp:20:
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginFactoryPrivate>; typename Wrapper::pointer = KPluginFactoryPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginfactory.h:408:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginFactoryPrivate>’ has no member named ‘data’
  999 | template <typename Wrapper> static inline typename Wrapper::pointer qGetPtrHelper(const Wrapper &p) { return p.data(); }
      |                                                                                                              ~~^~~~
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginLoaderPrivate>; typename Wrapper::pointer = KPluginLoaderPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginloader.h:422:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginLoaderPrivate>’ has no member named ‘data’
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KSycocaEntryPrivate>; typename Wrapper::pointer = KSycocaEntryPrivate*]’:
/usr/include/KF5/KService/ksycocaentry.h:139:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KSycocaEntryPrivate>’ has no member named ‘data’
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:63: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o] Error 1
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:76: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:516: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
[sudo] password for subh: 
[  4%] Built target org.kde.windowbuttons-plasmoids-metadata-json
[  9%] Automatic MOC for target appletdecorationplugin
[  9%] Built target appletdecorationplugin_autogen
[ 13%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o
In file included from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/moc_previewbridge.cpp:9,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/mocs_compilation.cpp:9:
/home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/previewbridge.h:53:10: error: ‘void Decoration::Applet::PreviewBridge::update(KDecoration2::Decoration*, const QRect&)’ marked ‘override’, but does not override
   53 |     void update(KDecoration2::Decoration *decoration, const QRect &geometry) override;
      |          ^~~~~~
In file included from /home/subh/anaconda3/include/qt/QtCore/qnamespace.h:43,
                 from /home/subh/anaconda3/include/qt/QtCore/qobjectdefs.h:48,
                 from /home/subh/anaconda3/include/qt/QtCore/qobject.h:46,
                 from /home/subh/anaconda3/include/qt/QtCore/qplugin.h:43,
                 from /home/subh/anaconda3/include/qt/QtQml/qqmlextensionplugin.h:43,
                 from /home/subh/anaconda3/include/qt/QtQml/QQmlExtensionPlugin:1,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/libappletdecoration/appletdecorationplugin.h:23,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/EWIEGA46WW/moc_appletdecorationplugin.cpp:9,
                 from /home/subh/Downloads/widgets/applet-window-buttons-master/build/libappletdecoration/appletdecorationplugin_autogen/mocs_compilation.cpp:2:
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginFactoryPrivate>; typename Wrapper::pointer = KPluginFactoryPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginfactory.h:408:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginFactoryPrivate>’ has no member named ‘data’
  999 | ypename Wrapper> static inline typename Wrapper::pointer qGetPtrHelper(const Wrapper &p) { return p.data(); }
      |                                                                                                   ~~^~~~

/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KPluginLoaderPrivate>; typename Wrapper::pointer = KPluginLoaderPrivate*]’:
/usr/include/KF5/KCoreAddons/kpluginloader.h:422:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KPluginLoaderPrivate>’ has no member named ‘data’
/home/subh/anaconda3/include/qt/QtCore/qglobal.h: In instantiation of ‘typename Wrapper::pointer qGetPtrHelper(const Wrapper&) [with Wrapper = std::unique_ptr<KSycocaEntryPrivate>; typename Wrapper::pointer = KSycocaEntryPrivate*]’:
/usr/include/KF5/KService/ksycocaentry.h:139:5:   required from here
/home/subh/anaconda3/include/qt/QtCore/qglobal.h:999:112: error: ‘const class std::unique_ptr<KSycocaEntryPrivate>’ has no member named ‘data’
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:63: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:516: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by psifidotos** [comment]
#131
