### ISSUE TITLE
Disable borders for maximized windows don't work after every start

### ISSUE THREAD

**Issue by Lewatoto** [psifidotos/applet-window-buttons#148]
Already had the option selected but i have to re enable on every new startup, besides this all seems to work ok, there is a way to debug this?

My system settings:
Windows Buttons Settings version = 0.9.0
Operating System: Fedora Linux 35
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Kernel Version: 5.14.15-300.fc35.x86_64 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
Memory: 15.3 GiB of RAM
Graphics Processor: AMD Radeon™ Vega 8 Graphics

**Comment by psifidotos** [comment]
The option has been totally dropped at v0.10

You have to enable it manually from v0.10 and later.
