### ISSUE TITLE
Applet doesn't hide itself if "Preserve as empty space" is choosen

### ISSUE THREAD

**Issue by second2050** [psifidotos/applet-window-buttons#149]
This applet seems to stay visible if:
"Show" is set to "Last active window is maximized" and
"Hidden State" is set to "Preserve as empty space".
and only hides itself if no window is on screen.
It hides itself correctly if "Hidden State" is set to "Slide out animation".

![out](https://user-images.githubusercontent.com/37344371/140965032-b1451668-675b-4f2e-aff1-ac8bc2ff3339.gif)

Versions I tested:
`community/plasma5-applets-window-buttons 0.10.1-1`
`aur/plasma5-applets-window-buttons-git 0.10.1.r0.ge2db5c0-1`

System Information:
OS: Arch Linux
KDE Plasma: 5.23.2
KDE Frameworks: 5.87.0
Qt: 5.15.2

**Comment by souvikhazra1** [comment]
I am also facing the same issue.

**Comment by psifidotos** [comment]
The video is not correct.
What would you except after minimizing the window?
all applets become hidden so how do you know that the applet does not "preserve as empty space"?

**Comment by psifidotos** [comment]
tested your settings in my system they work just fine....

**Comment by psifidotos** [comment]
> I am also facing the same issue.

I dont see any issue in the video, what do you mean?

**Comment by souvikhazra1** [comment]
Settings:
Hidden State: Preserve empty space
Show: Last active window is maximized

When the last active window is not minimized then it should not show the window controls, but it's still showing the window controls.

Settings:
Hidden State: Slide out animation
Show: Last active window is maximized

When the last active window is not minimized slides out and as soon as the window is maximized it slides back in, which works as expected.

Seems like "Hidden State: Preserve empty space" is having issue.

**Comment by second2050** [comment]
> The video is not correct. What would you except after minimizing the window? all applets become hidden so how do you know that the applet does not "preserve as empty space"?

Before it also hid itself _if the window is not maximized but visible_ with these settings which it now only does with the "slide out" animation.
