### ISSUE TITLE
Window buttons disappear when clicking on a tray icon

### ISSUE THREAD

**Issue by bidinou** [psifidotos/applet-window-buttons#15]
Hi ! 
I use the Window Buttons plasmoid without the "show only when active window is maximized" option, so I expect to see the applet at all times (handy to close / minimize several windows in a row).

However I noticed the applet buttons temporarily disappeared when I clicked on a tray icon like the "notification" or "volume" tray icon, which is a little annoying because if shifts the tray icon position so you have to move in order to click it again.

Cheers !

**Comment by psifidotos** [comment]
Feel to argue at https://github.com/psifidotos/applet-window-buttons/issues/4

**Comment by psifidotos** [comment]
![default](https://user-images.githubusercontent.com/2216474/48310777-11705200-e59d-11e8-8bd8-a4d052336050.png)

**Comment by bidinou** [comment]
Perfect, thank you ! :-)

**Comment by bidinou** [comment]
I don't know if that's related but after updating, all my windows decorations suddenly looked very big.
I tried to change the decorations settings in the control panel, but it made no difference !
Thus, I decided to delete all my config files.
The decorations went back to normal. Then I re-arranged my Latte dock and the decorations turned big again.

**Comment by bidinou** [comment]
See, before :  https://ibb.co/iBsmtV
After : https://ibb.co/cDuPDV

**Comment by psifidotos** [comment]
Increase your thickness margin

**Comment by bidinou** [comment]
I'm actually referring to my Kwin decorations thickness.

**Comment by psifidotos** [comment]
This is not related to this applet

**Comment by bidinou** [comment]
Hmm, this is strange, this started happening when I updated this morning it and is reverted after completely wiping my KDE config when I tweak Latte...

**Comment by bidinou** [comment]
(okay, this bug is indeed unrelated but has something to do with using font Roboto size 11 for windows titles... After rebooting, one gets HUGE decorations -- I guess I have to file a bug in kde against kwin or breeze)
