### ISSUE TITLE
Buttons are invisible with Plastik window decorations

### ISSUE THREAD

**Issue by Hate9** [psifidotos/applet-window-buttons#151]
The Decoration dropdown does not display Plastik as an option, and when the current system window decorations are Plastik and the Decoration dropdown has Current selected, the buttons display invisible.

**Comment by psifidotos** [comment]
Has Plastik been updated to KDecoration2 decorations?

**Comment by Hate9** [comment]
I'll be honest, I have no idea how to check.

**Comment by psifidotos** [comment]
it is a qml based aurorae theme that provides its own solution. There is no way for such implementations that do not provide an API or something to support them.

https://github.com/KDE/kwin/tree/master/src/plugins/kdecorations/aurorae/themes/plastik
