### ISSUE TITLE
[feature request] option to use image paths instead of window decorations

### ISSUE THREAD

**Issue by Hate9** [psifidotos/applet-window-buttons#152]
For the sake of compatibility with unhelpfully-developed window decorations (as mentioned in #151), would it be possible to add an option to select a set of images (or some form of preset spritesheet format) to use for buttons instead of window decoration styles?

**Comment by psifidotos** [comment]
this is exactly how Aurorae svg or png themes are supported. Make an aurorae theme with the needed icons and it should work just fine.
