### ISSUE TITLE
[feature] show for most recently active window on relevent screen

### ISSUE THREAD

**Issue by Hate9** [psifidotos/applet-window-buttons#153]
The buttons remain active as long as the last window to be active on the relevant screen is still active and still on said screen.
Same functionality as [/applet-window-appmenu/issues/183](https://github.com/psifidotos/applet-window-appmenu/issues/183) and [/applet-window-title/issues/122](https://github.com/psifidotos/applet-window-title/issues/122)

**Comment by psifidotos** [comment]
I can not implement this for plasma panels because it needs too mush ground work in order to support this with Plasma LibTaskmanager way of things.
It is already supported for Latte through Latte internal LastActiveWindow interface.
The best results are produced with Latte v0.10.4 or greater.
