### ISSUE TITLE
It seems it doesn't autocolor with kwinscript-window-colors

### ISSUE THREAD

**Issue by choyy** [psifidotos/applet-window-buttons#156]
The applet window title and appmenu works fine.

**Comment by psifidotos** [comment]
show me a screenshot to understand. What decoration are you using for the window buttons?

**Comment by choyy** [comment]
@psifidotos you mean this?
![图片](https://user-images.githubusercontent.com/68107073/145220131-a0967707-d14f-49b2-b17b-45b10fbdc386.png)

**Comment by psifidotos** [comment]
I want a full desktop screenshot showing the bug.

**Comment by psifidotos** [comment]
my guess is that the color scheme in the second screenshot is not properly set... to confirm this apply this color scheme to kwrite that is not client sided decorated, you will see that the kwrite titlebar wont paint the buttons correctly.

**Comment by choyy** [comment]
I apply the color scheme to Dolphin and it's the same situation.
![图片](https://user-images.githubusercontent.com/68107073/145323389-549ee52f-618a-4643-944e-25501c930473.png)

**Comment by psifidotos** [comment]
right click the applet and show me its configuration window

**Comment by choyy** [comment]
![image](https://user-images.githubusercontent.com/68107073/145355755-f6592047-1b2c-470d-80b2-b365f6ef94c0.png)

**Comment by psifidotos** [comment]
You need to set at your settings Colors: Current
Colors:Plasma Ttheme, means that it uses only the color palette of the plasma theme

**Comment by choyy** [comment]
Thanks a lot again!!
