### ISSUE TITLE
When panel is resized, the applet is not

### ISSUE THREAD

**Issue by felagund** [psifidotos/applet-window-buttons#159]
This is on Kubuntu 21.10 using Plasma panel.
Steps to reproduce:
1) Put the applet into a horizontal panel.
2) Change the panel size (say from 48 pixels to 32).
3) The size of the buttons does not change (I think restarting Plasma fixes it) like this:
![Screenshot_20211228_011416](https://user-images.githubusercontent.com/1218098/147562135-a6c77ba1-a1c4-4083-94e8-e40e8734c842.png)
:

**Comment by psifidotos** [comment]
Oh this is upstream issue and has been fixed with Plasma 5.23, I am the one implemented the fix.

Your Plasma version is probably outdated.

**Comment by felagund** [comment]
Yeah, thanks, I am on Plasma 5.22. Great it has been fixed, thank you.
