### ISSUE TITLE
Applet is not visible until panel is first resized

### ISSUE THREAD

**Issue by krisives** [psifidotos/applet-window-buttons#16]
When I first login to KDE the applet is not visible or is somehow resized such that it cannot be seen. However, after hitting the Plasma hamburger menu once it then appears. I have the setting "Show only when active window is maximized" as well as `BorderlessMaximizedWindows=true` in my `~/.config/kwinrc` file, if that matters.

KDE Neon
KDE 5.14.3

**Comment by psifidotos** [comment]
are you using latest master ?

**Comment by psifidotos** [comment]
this has been fixed in master

**Comment by krisives** [comment]
Thanks I didn't see it was fixed, I was using 5f84002 and just updated to a1d2212
