### ISSUE TITLE
ppa dependencies: libkdecorations2private7

### ISSUE THREAD

**Issue by spbisc97** [psifidotos/applet-window-buttons#163]
First, thanks for your work.
KDE Neon User Edition
Linux 5.13

I tried to use the PPA to install applet-windows-buttons but I was unable to install it because of the libkdecorations2private7 dependence. I think now the main version is libkdecorations2private9 and to install old version apt would need to remove the entire desktop. 

Anyway, i have installed the applet through install.sh and is working fine. Thanks for your product!

**Comment by psifidotos** [comment]
Neon User Edition needs to update its version and rebuild it of course
