### ISSUE TITLE
After upgrading to Plasma 5.24 generic windows buttons are used.

### ISSUE THREAD

**Issue by aliquo93** [psifidotos/applet-window-buttons#164]
Hi, when I was on Plasma 5.23 the applet showed the same buttons as my Plasma decorations theme:

![XxmnN9y](https://user-images.githubusercontent.com/9071297/153061910-847f42f4-6592-4368-8ca5-ecd90f2fd8c1.png)

After upgrading to Plasma 5.24, it shows a generic theme instead, even if in the applet settings I''ve set the decoration option to "Current".

![Screenshot_20220208_203627](https://user-images.githubusercontent.com/9071297/153062460-1dba1c63-23ad-4be7-b716-223368103aa8.png)

**Comment by psifidotos** [comment]
#155
