### ISSUE TITLE
buttons are not the same with the theme selected even after changing 

### ISSUE THREAD

**Issue by exxmen** [psifidotos/applet-window-buttons#165]
![image](https://user-images.githubusercontent.com/4624303/153267716-58a6cd9f-7d4d-40e5-8037-345c841a3088.png)

EDIT: It was working fine up until I updated to Plasma 5.24.0

**Comment by Fosssil** [comment]
Same Here

**Comment by Fosssil** [comment]
**Same here....**
_Additional info:_ 
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Graphics Platform: X11

**Comment by psifidotos** [comment]
#155
