### ISSUE TITLE
Buttons are not same in plasma 5.24

### ISSUE THREAD

**Issue by Fosssil** [psifidotos/applet-window-buttons#166]
**Hello @psifidotos,** 
**Buttons are not looking same in title bar and latte panel after I updated my system to latest plasma 5.24
I have five systems running the same layout all of them are facing this same issue.**

**_Additional information:_**
Operating System:              Arch Linux
KDE Plasma Version:         5.24.0
KDE Frameworks Version: 5.90.0
Qt Version:                          5.15.2
Kernel Version:                   5.16.7-arch1-1 (64-bit)
Graphics Platform:               X11

**_Screenshot:_**
![Screenshot_20220210_003307](https://user-images.githubusercontent.com/38956299/153272594-6e6315a9-b73d-4dde-a19a-af37f2bb805b.png)

Thank you

**Comment by michaldybczak** [comment]
I confirm this issue. This happens if we choose a usual aurorae theme. If we choose Breeze or Breeze fork it works, kinda (some issues are there still).

I already recompiled the applet and latte, restarted system, didn't help. In settings, we have set Current, but it uses breeze default instead.

**Comment by psifidotos** [comment]
#155
