### ISSUE TITLE
Fix for wrong Buttons did not help

### ISSUE THREAD

**Issue by Ronnie1320** [psifidotos/applet-window-buttons#168]
Hi @psifidotos !
I am using Garuda Linux too, like in #155 .
Unfortunately, it seems like your newest Release 0.11.1 did not fix the Problem.
Do you need more log informations to fix this?

And, maybe you did not recognize it, but in the help there stands still I am using Version 0.10.1 although
I even used the original source and not the release.

Thanks for your great work,
Ronnie1320

**Comment by psifidotos** [comment]
I am using Tumbleweed, works perfectly fine for me

**Comment by psifidotos** [comment]
#155

**Comment by Durus-R** [comment]
No it is working again.
No clue why, but it is still Version 0.10.1.

Thanks again for your Engagement on Plasma Applets.
