### ISSUE TITLE
When set to hide ( not always visible ) the "always on top button" stays visible

### ISSUE THREAD

**Issue by alexjp** [psifidotos/applet-window-buttons#170]
When, in the Show options, using an option like "Active window is present", if I have the "always on top" button stays visible.

**Comment by psifidotos** [comment]
show me a screenshot to understand the issue

**Comment by alexjp** [comment]
Visible (with active window): 
![visible](https://user-images.githubusercontent.com/85806/153762405-1ff1aa0a-c30b-40af-b1b0-0849c10acfa7.png)


Hidden (without any window):
![hidden](https://user-images.githubusercontent.com/85806/153762421-2d5d9e45-c6a8-454b-acfa-05a4628020a9.png)

**Comment by psifidotos** [comment]
this is not reproducable in my latte panel. 

1. Are you using latte or plasma panel?
2. what is your applet version?
3. show me a screenshot of the applet settings window

**Comment by alexjp** [comment]
1. latte dock panel ( no plasma panels active )
2. although pacman says: `community/plasma5-applets-window-buttons 0.11.1-1 [instalado]`
![image](https://user-images.githubusercontent.com/85806/153765577-46f00283-7767-4822-83f0-73760eb69137.png)

3.
![image](https://user-images.githubusercontent.com/85806/153765556-e1a013da-b5b8-4977-b3cd-99952cef7d7a.png)

currently in those settings, I have the troubling button hidden, because its the workaround I am using. but of course, it happens with it enabled!

**Comment by alexjp** [comment]
ok... discovered what was happening, and why the version numbers were different.

there were another older installation of this applet that was in conflict. now it displays proper 0.11.1 version and this bug report is invalid!

EDIT: forgot to say, sorry for the bad issue reported. Thank you for your time!
