### ISSUE TITLE
BUG : buttons forgets position after restart.

### ISSUE THREAD

**Issue by vyrsh** [psifidotos/applet-window-buttons#171]
![Screenshot_20220213_181929](https://user-images.githubusercontent.com/61771930/153753959-6e289775-644f-4664-ba3a-153e4f6b854c.png)

Whenever I restart, I find the buttons to be placed there. 
I enter plasma edit mode, and place the buttons in top left position, and it stays there without any errors.
but it returns back to the position in the image after restart.

these are my settings.

![Screenshot_20220213_182443](https://user-images.githubusercontent.com/61771930/153754123-a4b80827-4e21-4641-951b-ae0a921ed948.png)

the applet version is 0.10.1, and plasma version is 5.24, but the problem was there in 5.23.5 too.
EDIT : tested with the new 0.11.1 applet, and the problem is still there.

**Comment by vyrsh** [comment]
just installed 0.11.1, and the same problem is still there.

**Comment by psifidotos** [comment]
plasma panels bug... nothing related to the applet...
you can use Latte panels if this is so important for you.
