### ISSUE TITLE
Installation failed, what else do I need to do?

### ISSUE THREAD

**Issue by Jsin99x** [psifidotos/applet-window-buttons#172]
Make Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:19 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:20 (find_package):
  Could not find a configuration file for package "KDecoration2" that is
  compatible with requested version "5.24.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5
    /usr/lib/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5
    /lib64/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5
    /lib/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5

**Comment by psifidotos** [comment]
This is no help forum, you need to use your distro forums, etc.
