### ISSUE TITLE
Update the AUR package

### ISSUE THREAD

**Issue by Fosssil** [psifidotos/applet-window-buttons#173]
Hello again @psifidotos,
If you are the maintainer of this package for **AUR** on arch linux then I request you to update it to latest version as it is _flagged as out-of-date_ package on 2022-02-12.
_Link- https://aur.archlinux.org/packages/applet-window-buttons-git_
I hope you will consider the request.
Thank you.

**Comment by psifidotos** [comment]
I dont do packaging, you need to contact your distro
