### ISSUE TITLE
Installation failed, what else do I need to do ？

### ISSUE THREAD

**Issue by Jsin99x** [psifidotos/applet-window-buttons#174]
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:19 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5CoreAddons: /usr/lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.90.0") 
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Declarative: /usr/lib64/cmake/KF5Declarative/KF5DeclarativeConfig.cmake (found version "5.90.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found KF5Plasma: /usr/lib64/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.90.0") 
-- Found KF5PlasmaQuick: /usr/lib64/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.90.0") 
-- Found KF5: success (found suitable version "5.90.0", minimum required is "5.81.0") found components: CoreAddons Declarative Plasma PlasmaQuick 
CMake Error at CMakeLists.txt:20 (find_package):
  Could not find a configuration file for package "KDecoration2" that is
  compatible with requested version "5.24.0".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5
    /usr/lib/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5
    /lib64/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5
    /lib/cmake/KDecoration2/KDecoration2Config.cmake, version: 5.23.5

-- Configuring incomplete, errors occurred!
See also "/home/admin/Desktop/applet-window-buttons-master/build/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
make: *** 没有规则可制作目标“install”。 停止。

**Comment by trmdi** [comment]
You asked this once: https://github.com/psifidotos/applet-window-buttons/issues/172

And that was closed because this is not the right place for asking this kind of question. You could ask this in forums, reddit...

// from the log, you can see it requires KDecoration 5.24 while you only have 5.23.5

**Comment by Jsin99x** [comment]
Im sorry. :(
Because of the latest kdecoration on my side...
2 aur/kdecoration-git 5.23.80_r273.g343cade-1 (+13 0.02)
        Plugin-based library to create window decorations
1 extra/kdecoration 5.23.5-1 (73.4 KiB 280.6 KiB) [plasma]

**Comment by trmdi** [comment]
No idea, you should ask on reddit.com/r/ArchLinux or Manjaro depends on your distro.
(Manjaro often gets updates more slowly than Arch...)
