### ISSUE TITLE
[feature] button appear only on app that use system titlebar but was hidden

### ISSUE THREAD

**Issue by negadecade** [psifidotos/applet-window-buttons#175]
hello sir, is it possible to make the button to appear only for apps that make use of system titlebar as currently i dont think it is possible to make the window button for gtk apps with headerbar disappear and it would be weird if certain apps has duplicate button on both the apps and the panel. 
for example, when the apps has a titlebar and it is hidden (such as when maximized), the button will then automatically appear

**Comment by psifidotos** [comment]
this is GTK responsibility to fix
