### ISSUE TITLE
Buttons theme does not update on Plasma v5.24.3

### ISSUE THREAD

**Issue by tnilzon** [psifidotos/applet-window-buttons#176]
Can't get the buttons theme to update to used global theme window buttons theme.

>My system:
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.3
Kernel Version: 5.16.14-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-9700K CPU @ 3.60GHz
Memory: 31,2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by psifidotos** [comment]
use latest version

**Comment by tnilzon** [comment]
OK, I realized that my installed version was v0.10.0, so I followed your advice and updated to v0.11.1, and now it works like a charm, thanks for your help!
