### ISSUE TITLE
Lose response after sleeping and waking up

### ISSUE THREAD

**Issue by ZJsheep** [psifidotos/applet-window-buttons#177]
After I sleep my laptop and wake it up again, there are chances that the applet lose its function. Buttons are there, but clicking does not produce any response. I have to remove them and add them back each time such things happen.

My environment is Kubuntu 20.04.3, with KDE 5.68.0 / Plasma 5.18.8. I install the app using apt.

**Comment by psifidotos** [comment]
your plasma and frameworks are too old... no idea if that is the reason... in my laptop with Plasma 5.24 I dont have such issue.
