### ISSUE TITLE
Window Buttons not clickable in corner of the screen

### ISSUE THREAD

**Issue by v1-valux** [psifidotos/applet-window-buttons#179]
Under normal circumstances, the Window Buttons were clickable when the Mouse was on the edge of the monitor (upper right corner).

Now you need to move the mouse slightly out of the edge (on the close button), to close windows.
It is only 1 pixel, but makes huge difference in my opinion.

I experience this since one of the last updates.

Is this expected behavior? Because for me it was convenient just to click into the corner of the screen to close an open window.

**Comment by psifidotos** [comment]
it works just fine for me...

**Comment by v1-valux** [comment]
I'm using Manjaro (release 21.2.6-1) with plasma-desktop 5.24.5-1, changed none of my related settings since (also switched to default themes/settings for testing) and I do not know any solution to make it corner-clickable again, while another widget ("application-overview") is still clickable out in the corners.

Maybe I experience this as a weird buggy combination of themes or appearance settings but I still just wanted to know if it could be code related..

Thanks for the response though.
If you know any way for me to debug this please let me know.

EDIT: I noticed only the right side of the screen is problematic, if I move the mouse 1px horizontally to the left, it is responsive.
maybe some global "deadzone" I cannot find.
