### ISSUE TITLE
"Thickness margin" option returns a weird result

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-buttons#18]
I think there is something wrong with the latest commit.
Before that, change `Thickness margin` make the buttons smaller, but after that, they look like this:

Thickness margin: 10px
![image](https://user-images.githubusercontent.com/11857205/48329858-14db0a80-e67d-11e8-9bcb-b030f962072c.png)

The same result with Breeze.

**Comment by psifidotos** [comment]
> Before that, change Thickness margin make the buttons smaller

give me screenshots before and after and what theme you are using...

**Comment by psifidotos** [comment]
@trmdi check with latest master... you will see that this is BreezeEnhanced issue... I found a small fix in the geometry calculations but you will notice that even though Breeze works just fine, BreezeEnhanced it does not....

If you check with v0.1 will see again that BreezeEnhanced still does not shrink/enlarge accordingly. This theme possibly it does not take into account the provided space it paints its buttons according to the user preference for icon size... small, huge etc. etc...

so this is upstream issue for BreezeEnhanced

**Comment by trmdi** [comment]
Well, with the latest commit f5c8a09, the size is customizable now.
But even when Icon spacing is 0px, the space is still too far:
![image](https://user-images.githubusercontent.com/11857205/48360740-724d7680-e6d2-11e8-977b-3cc3c77c4f09.png)
I wish I could reduce the space a bit more.

**Comment by psifidotos** [comment]
> But even when Icon spacing is 0px, the space is still too far..

yes, following Fitt's law and at the same time provide good geometry, is not that easy...
I will have to raise the awesomeness of that applet...

**Comment by psifidotos** [comment]
@trmdi I really like how it behaves with last commit... please try again...

**Comment by trmdi** [comment]
Yeah, it is pixel perfect now. Thank you very much !
![image](https://user-images.githubusercontent.com/11857205/48365128-9c0b9b00-e6dc-11e8-87e6-b7321e979b66.png)

**Comment by psifidotos** [comment]
> Yeah, it is pixel perfect now. Thank you very much !

;)
