### ISSUE TITLE
buttons do not render in any version installed. common resource missing/not addressed in deps?

### ISSUE THREAD

**Issue by dantedwards** [psifidotos/applet-window-buttons#185]
OS: EndeavourOS Linux x86_64
kernel: 5.19.12-arch1-1
desktop: Plasma 5.25.5

buttons fail to render in any version of the applet installed. i've built 0.11.1 and 0.10.1 from ocs via kde store, installed from arch community repositories, and built from git, but they all give the same error fairly early in main.qml at line 26:

file:///usr/share/plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: module "org.kde.appletdecoration" is not installed

a quick search of / shows that i in fact do not have that module installed. i've verified that i have all the required dependencies, and cmake seems to indicate that i do as well. i don't know what package installs this module; all the searching i've done for org.kde.appletdecoration won't point me to anything useful

![image](https://user-images.githubusercontent.com/103319956/193436424-58af524a-66f9-489f-996c-ea5c0c3f119b.png)

**Comment by psifidotos** [comment]
you miss the library...
I have reported that: https://store.kde.org/p/1906579  is spam but noone cares at kde store.

**Comment by dantedwards** [comment]
okay, but i'm misisng the library even when i install from your git. do you have a link to an install for this lib?

**Comment by psifidotos** [comment]
> okay, but i'm misisng the library even when i install from your git. do you have a link to an install for this lib?

did you read the README? you need to run `sh install.sh`, the library is built and installed in your system though the install script.

**Comment by Cequallium** [comment]
I'm having the same issue even though i did exactly as said, I am also on Endeavor OS, i've checked and i have all the dependencies and they are all on the same versions required or above

here are some of the cmake warnings I got while running ./install.sh.

```
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:113 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:19 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5: success (found suitable version "5.99.0", minimum required is "5.81.0") found components: CoreAddons Declarative Plasma PlasmaQuick 
-- KDECORATION2 VERSION MINOR : 26
-- Could not set up the appstream test. appstreamcli is missing.
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:113 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  libappletdecoration/CMakeLists.txt:37 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5: success (found suitable version "5.99.0", minimum required is "5.26.0") found components: Plasma WindowSystem I18n Service ConfigWidgets 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cequal/applet-window-buttons/build
[  4%] Automatic MOC for target appletdecorationplugin
[  4%] Built target appletdecorationplugin_autogen
```

**Comment by Cequallium** [comment]
Update, Restarting fixes it, Thank you for this awesome applet.
