### ISSUE TITLE
Support multi-screen aware option

### ISSUE THREAD

**Issue by Zardoz89** [psifidotos/applet-window-buttons#22]
Get the behavior filter option, like haves applet-window-title, for multi-screen setups. Actually only works correctly if the window is on the same screen that the widget.

**Comment by psifidotos** [comment]
Please provide a screenshot and be more specific

**Comment by Zardoz89** [comment]
![screenshot_20181120_101014](https://user-images.githubusercontent.com/888483/48762975-8550df80-ecac-11e8-834f-d422a9ecdd58.png)

It click to maximize (or any other button of this applet) and simply ignores it, if the focused window is on the left screen. This applet is what is place next to the green plot on the upperbar (the buttons at the top right is AWC running)

**Comment by psifidotos** [comment]
You mean that you want to able to handle the left window from the right screen ?

**Comment by psifidotos** [comment]
you can test it and provide feedback...

**Comment by Zardoz89** [comment]
Well... no works.

I upload a video of what it does : 
[video.zip](https://github.com/psifidotos/applet-window-buttons/files/2610136/video.zip)

**Comment by psifidotos** [comment]
> Well... no works.

Well... yes it works just fine in my system...
with the following settings enabled:

![default](https://user-images.githubusercontent.com/2216474/48944526-c86eb500-ef2f-11e8-85bf-15bc7318073a.png)

**Comment by psifidotos** [comment]
but... there are some corner cases I dont know why yet that after you enable your screen aware settings you must go to Latte Edit mode and back to normal again...

**Comment by psifidotos** [comment]
@Zardoz89 the problem lead to Latte the plasmoid.screenGeometry value was not updated correctly whenever there were screen changes... 

for proper multi-screen aware states from plasmoids in Latte you must use latest Latte git version or upcoming stable version 0.8.3

**Comment by Zardoz89** [comment]
1. Yes, its now working. Perhaps I need to restart the KDE session to get it working correctly.
2. @psifidotos I know that I can make any qty of panels. I have a second panel on a lateral with a icon taskbar and a few widgets more. I simply not like to add a panel on the other screen becasue I like to use the full screen when I maximize something there. 
3. I'm not using Latte dock
