### ISSUE TITLE
Window buttons don't work if you create a second activity.

### ISSUE THREAD

**Issue by ripefig** [psifidotos/applet-window-buttons#23]
Using latest latte-dock package from git master and wm-buttons from source.

If you add a second activity, the buttons no longer work. Everything else seems to work. Even after you remove the activity, they still don't work. Hopefully it can be resolved with a logout.

**Comment by psifidotos** [comment]
what you mean they dont work? I cant reproduce...

can you make a video and upload it at google drive?
