### ISSUE TITLE
Aurorae themes can not produce icon spacing 0px. when thickness margin>0px.

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/applet-window-buttons#24]
After update to 0.2-1 buttons spacing increased. So I went to settings and started lowering it. I discovered few things:

- if lowering the value, even numbers have no effect, if increasing value, odd numbers have no effect - just change the value from 0 to 12 and 12 to 0 one by one and apply settings to see what I mean,
- after lowering spacing to zero there is still lots of space between icons, previously they were touching each other which made sense, given the number zero

Current spacing set to zero is OK for me, but what if someone wants to make it even lower?

Here is how buttons look like with spacing set to zero:

![screenshot-2018-11-24-13-49-14](https://user-images.githubusercontent.com/10132958/48968421-df74dc00-efef-11e8-8911-6b6ae0a32b49.png)
Maybe that's intended feature? As already said, the effect is good, just as I prefer, but I can imagine someone wants it to be tighter.

Also other parameters have changed. Before left margin needed to be 3 for the first button not to touch the edge of the screen. Now I set it to zero and there is still space. It's good, but I kind liked previous effects. They were logical and allowed for full customization. Zero meant zero and now zero means something else. I had control over the space and now I have a nice space which is good but is not controllable.
Is that intended feature? If so, it's not bad, but again, I liked the full control feeling I got with the old settings.

Aside from that, all looks fine, there is no longer the bug with applet not being possible to remove or move in latte edit mode.

**Comment by psifidotos** [comment]
What is you decorations theme?

**Comment by michaldybczak** [comment]
It's breezmite, breeze looks completely different and has exactly the same behavior. What theme did you mean? Aurorae? This has no influence on it, those issues still exits. Desktop theme? System theme? Will experiment.

**Comment by psifidotos** [comment]
@michaldybczak fixed in master version

**Comment by michaldybczak** [comment]
Thanks :)
