### ISSUE TITLE
Color of buttons is not always painted properly for Breeze themes

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-buttons#25]
When I try SierraBreezeEnhanced buttons (Decoration style: Always inactive) with Breeze colorscheme:
![buttonscolor](https://user-images.githubusercontent.com/11857205/49009829-1e4b9300-f1a4-11e8-8451-29c1bde08009.gif)

The same result with Breeze buttons:
![image](https://user-images.githubusercontent.com/11857205/49010407-be55ec00-f1a5-11e8-9bd6-8a1412f37443.png)
 
I think the color should be responsive like the color of Appmenu as well as other applets. It should somehow depend on the background color.

(Plasma theme: Breeze, System color: Breeze)

**Comment by kupiqu** [comment]
Did you try setting the Decoration to Current? Or if you want to set it manually, set Decoration to SierraBreezeEnhanced

Not sure this will solve the issue, but it will pick the proper Decoration Style. I think you have a miz in Breeze perhaps, coming from my issue number 1 that you reported.

**Comment by trmdi** [comment]
It seems that the buttons color does not depend on the background color, while the panel color (the background) changes between black and white/transparent.

**Comment by psifidotos** [comment]
> SierraBreezeEnhance

When you use Breeze as decoration theme do you have this issue?

**Comment by psifidotos** [comment]
I am asking because the Buttons applets is not painting anything... It passes to decoration theme the colorscheme and the decoration theme paints accordingly ...

So this is not a request for the Buttons applet but rather for SieraBreezeEnhanced developer to paint its buttons based on the colorscheme....

**Comment by trmdi** [comment]
> > SierraBreezeEnhance
> 
> When you use Breeze as decoration theme do you have this issue?

Yes, as I said in post#1.

**Comment by psifidotos** [comment]
> Yes, as I said in post#1.

In the Buttons applet choose:
Theme: Breeze
Colors: Current

it doesnt update accordingly when needed with Latte git version?

**Comment by trmdi** [comment]
> > Yes, as I said in post#1.
> 
> In the Buttons applet choose:
> Theme: Breeze
> Colors: Current
> 
> it doesnt update accordingly when needed with Latte git version?

Yes. Latte git version.
![image](https://user-images.githubusercontent.com/11857205/49015494-d59cd580-f1b5-11e8-80ed-babbeb967046.png)

**Comment by psifidotos** [comment]
Enable in Latte: Monochrome contents when panel is transparent

Does it help?

**Comment by trmdi** [comment]
> Enable in Latte: Monochrome contents when panel is transparent
> 
> Does it help?

No, it doesn't:
![image](https://user-images.githubusercontent.com/11857205/49015731-8c00ba80-f1b6-11e8-939e-223f31bade90.png)

**Comment by psifidotos** [comment]
> No, it doesn't:

Enable in Latte: "Hide background for not maximized windows"

does it help?

**Comment by trmdi** [comment]
> > No, it doesn't:
> 
> Enable in Latte: "Hide background for not maximized windows"
> 
> does it help?

Neither. It works on your computer?

**Comment by psifidotos** [comment]
> Neither. It works on your computer?

yes, I have no issues with this...

**Comment by psifidotos** [comment]
This is my layout if you want to test it: 
[MyLayout(x11).layout.latte.txt](https://github.com/psifidotos/applet-window-buttons/files/2615661/MyLayout.x11.layout.latte.txt)


Just remove the txt extension before importing

**Comment by trmdi** [comment]
Ok, I will do.
But do you think you should add a rectangle background with the right color from the colorscheme under the buttons in the config window?
![image](https://user-images.githubusercontent.com/11857205/49016335-6379c000-f1b8-11e8-9cf2-a7ed6bce0396.png)

**Comment by trmdi** [comment]
> This is my layout if you want to test it:
> [MyLayout(x11).layout.latte.txt](https://github.com/psifidotos/applet-window-buttons/files/2615661/MyLayout.x11.layout.latte.txt)
> 
> Just remove the txt extension before importing

Here is your layout, I don't know whether the color of the buttons is right or wrong:
![image](https://user-images.githubusercontent.com/11857205/49017371-4bf00680-f1bb-11e8-8ac8-e398f49456f2.png)

**Comment by psifidotos** [comment]
They should be the same color with your applets

**Comment by psifidotos** [comment]
Are you using latest git version?

**Comment by trmdi** [comment]
> Are you using latest git version?

Yes, both of them:
```
❯ zypper if latte-dock applet-window-buttons | grep -i version
Version        : 999.git.20181125.74f80cd4-95.1               
Version        : 999.git.20181124.da3d3d2-16.1
```

**Comment by trmdi** [comment]
> either way... this is a Latte issue.. open a bug report for Latte to keep record... it is probably some Latte settings combination that breaks it...

I've opened it here: https://bugs.kde.org/show_bug.cgi?id=401431

**Comment by psifidotos** [comment]
@trmdi what is your Show option ?

**Comment by trmdi** [comment]
After upgrading, the color doesn't change from dark <-> white when change the focus/(un)maximize windows, like the video I attached in the Latte bug report. Something has been improved.

But, the main bug still exists. It seems the button applet doesn't know the current color correctly.
![image](https://user-images.githubusercontent.com/11857205/49697088-a63e8d80-fbe5-11e8-926f-110fb99e9c20.png)
![buttons](https://user-images.githubusercontent.com/11857205/49697116-12b98c80-fbe6-11e8-8265-a443a394e2fb.gif)

**Comment by psifidotos** [comment]
> But, the main bug still exists. It seems the button applet doesn't know the current color correctly.

applet does not paint anything, it just passes the color scheme file to the decoration to paint itself...
let's try and see what color file is passed... 

1. run latte from a terminal with 'latte-dock -d'
2. what is the terminal output when playing with this?

**Comment by psifidotos** [comment]
@trmdi ok I found a way... please retest with latest Latte git version and Buttons master version

**Comment by trmdi** [comment]
![buttons](https://user-images.githubusercontent.com/11857205/49698531-b6f7ff00-fbf7-11e8-9da2-3f00305e7c4b.gif)

On my computer, it looks like the color of the buttons is inverted.
```
[debug 21:11:08.449449] - buttons scheme update to: "/tmp/lattedock-EHKYUh/reversed.colors"
[debug 21:11:08.453453] - buttons scheme update to: "/tmp/lattedock-EHKYUh/reversed.colors"
[debug 21:11:10.364364] - buttons scheme update to: "/usr/share/color-schemes/Breeze.colors"
[debug 21:11:10.368368] - buttons scheme update to: "/usr/share/color-schemes/Breeze.colors"
[debug 21:11:15.516516] - buttons scheme update to: "/tmp/lattedock-EHKYUh/reversed.colors"
[debug 21:11:15.521521] - buttons scheme update to: "/tmp/lattedock-EHKYUh/reversed.colors"
```

**Comment by psifidotos** [comment]
Hm what is your plasma theme?

**Comment by psifidotos** [comment]
Reversed color scheme is used when the underlying background needs a scheme with higher contrast

**Comment by trmdi** [comment]
> Hm what is your plasma theme?

The stock theme `Breeze`.
If I change it to `Breeze Light` (the stock theme too), it looks like this :|
![image](https://user-images.githubusercontent.com/11857205/49699136-05110080-fc00-11e8-9163-620b6a0723af.png)

**Comment by psifidotos** [comment]
@trmdi ok found it... 

both are bugs breeze colors schemes, they are setting their WM colors faulty...
try to load the color scheme from plasma light theme and you will understand what is happening...

So Latte probably should take into account this and update the WM records in the theme file accordingly when that color palette is used from a plasma theme

**Comment by psifidotos** [comment]
ok... this must have been fixed from: https://bugs.kde.org/show_bug.cgi?id=401431

**Comment by trmdi** [comment]
Ok, well done. Thank you !

**Comment by kupiqu** [comment]
@trmdi could you please test if it also works fine when using sierrabreezeenhanced with the following two options enabled

- inactive window button style
- match title bar to window background

when using it on a dark latte panel?

this is the only configuration that fails in my system: I (barely) see dark buttons over the dark background. But I am using stable latte-dock not master and would highly appreciate if you could tell me if it works fine (or not) when using master.

thanks in advance!

**Comment by trmdi** [comment]
> could you please test if it also works fine when using sierrabreezeenhanced with the following two options enabled...

I don't see any problem.
![buttons](https://user-images.githubusercontent.com/11857205/49916514-d4fe8180-fecd-11e8-9487-6a80bf049ec2.gif)

**Comment by kupiqu** [comment]
Awesome, thank you @trmdi for testing it! and thank you @psifidotos for the feature!

**Comment by psifidotos** [comment]
> Awesome, thank you @trmdi for testing it! and thank you @psifidotos for the feature!

nice! That feature was puzzling in my head a lot of time! With Plasma 5.15 that will be more awesome because I will be able to provide a kwin script that informs Latte for touching windows, so if the user has choose a different color scheme for some apps then this apps will look consistent with the top bar. That is demonstrated through:

https://www.youtube.com/watch?v=QkPv0-tfsXk

notice that because kwrite has a reddish theme the top bar is colored accordingly..


Missing pieces from master:

1. The entire codepage is updated in order to be more readable and maintainable, both for qml and c++ parts
2. All applets will be offered through kde store, including Latte Spacer and new Latte Separator... that way will be improved also its use for plasma panels
3. Panel new coloring must become multi-screen aware
4. All the View Settings (old Dock/Panel settings) will be reorganized. The settings window will offer three states instead of two. Currently is (Basic/Advanced). In new settings it will be (Basic/Advanced/Extreme).
Tweaks will be dropped and all its be moved to appropriate tabs. I think that will be (Behavior/Appearance/Effects/Tasks)

Basic will be the current mode,
Advanced will be the current mode with some added options from Basic
Extreme will offer all the settings but not only that, the Settings window will be moved at the edge of the screen and it is height will use all the available screen height, something like the Deepin Control Center.

In View Settings it will offered also a way to hide completely the editMode background in order for the user to notice the difference of its settings (e.g. shadows, effects etc.) runtime comparing for example the contrast that settings provide based on the current underlying desktop background.

**Comment by kupiqu** [comment]
Nice!

**Comment by trmdi** [comment]
Hey, I just want to say thank you for everything you've done. Happy new year!

**Comment by psifidotos** [comment]
thank u!!!

@trmdi btw did you check the new advanced dock settings in git version? I haven't taken any feedback from community and I really like it

**Comment by psifidotos** [comment]
@trmdi happy new year to you too!!

**Comment by miyaokamarina** [comment]
@psifidotos, what about non-Breeze themes? I use Materia Dark, and it works great with dark windows, but makes buttons invisible with light ones. Non-Latte plasmoids have an option to enable shading (I use it for tray applet), but this applet does not allow it.

**Comment by psifidotos** [comment]
@miyaokamarina can you provide screenshots demonstrating the issue and what do you mean by shading as solution?

**Comment by miyaokamarina** [comment]
Here is my setup. I added two color picker applets to illustrate painting (both are with the same color; one with enabled “Enable painting for this applet” feature, other with disabled).

When Chrome window active (buttons invisible):

![Screenshot_20190704_141612](https://user-images.githubusercontent.com/37388187/60662854-24a29b80-9e66-11e9-9fe0-b8e2a047e52c.png)

When Telegram window is active (buttons visible):

![Screenshot_20190704_142253](https://user-images.githubusercontent.com/37388187/60663143-143ef080-9e67-11e9-869a-8eb094d26dc5.png)

**Comment by psifidotos** [comment]
1. Are you using Plasma or  Latte top panel?
2. If Latte, git or version 0.8?

**Comment by miyaokamarina** [comment]
1. That’s Latte panel.
2. I’m on git 971e67f6 version from archlinuxcn repo.

**Comment by psifidotos** [comment]
3. Have you installed and enabled the Latte Window Colors script?
4. Have you enabled at Window Buttons applet: Current?

**Comment by miyaokamarina** [comment]
Yes, I use Latte Window Colors. I can’t use Current option in Window Buttons. I use Breeze decorations in KWin, because it allows me to remove borders and titles (unlike Materia), but I use Materia Dark theme in Window Buttons applet. When I select Current/Breeze decorations in Window Buttons and Current colors, everything works fine ofc. Except that I don’t want Breeze icons. When I select Materia decorations in Window Buttons, I cannot anymore select Current colors.

**Comment by kupiqu** [comment]
That may be a problem with Aurora themes. 

Not sure this will be useful for you, but perhaps you could give Sierra Breeze Enhanced a try (https://github.com/kupiqu/sierrabreezeenhanced). In its settings you can specify a Gnome style similar to Materia...

**Comment by psifidotos** [comment]
Long story short, Aurorae themes like Materia Dark can NOT support dynamic coloring

**Comment by miyaokamarina** [comment]
@kupiqu, that looks great! It doesn’t exactly match Materia KDE theme, but looks good to me.

@psifidotos, I understand it, but if I understand correctly dynamic coloring may be supported for entire applet (like for all other non-Latte applets).

**Comment by psifidotos** [comment]
the problem is that Aurorae themes are svg or png files. So dynamic coloring is not possible, of course if someone appears with a magic patch supporting this I have no objection but I wouldn't bet on it

**Comment by kupiqu** [comment]
SVG files are XML files, so changing colors there is easy by match and replace. The problem is knowing which ones to change.

PNG files are an entirely different thing.

**Comment by miyaokamarina** [comment]
Both PNG and SVG may be titned with SVG filters.

![Screenshot_20190705_182024](https://user-images.githubusercontent.com/37388187/60731933-7411c600-9f51-11e9-994d-c68eff54d342.png)

![Screenshot_20190705_182004](https://user-images.githubusercontent.com/37388187/60731937-76742000-9f51-11e9-9f0a-979432fa2880.png)

![Screenshot_20190705_182032](https://user-images.githubusercontent.com/37388187/60731941-783de380-9f51-11e9-9786-7f88ae191800.png)

**Comment by psifidotos** [comment]
Yeah ok... feel free then to send patches for review then
