### ISSUE TITLE
Please add to readme

### ISSUE THREAD

**Issue by yalok** [psifidotos/applet-window-buttons#28]
To compile on ubuntu, one needs to install the libs first:
`sudo apt install g++ extra-cmake-modules qtbase5-dev qtdeclarative5-dev libkf5declarative-dev libkf5plasma-dev libkdecorations2-dev gettext`

**Comment by psifidotos** [comment]
feel free to make Pull Requests for Installation.md file... that file is provided to distros/users in order to update properly their distro specific commands for a successfull installation
