### ISSUE TITLE
[Feature request] Add the Configure button for the current decoration.

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-buttons#29]
That button will open the system setting module for that decoration, like when you open it from Alt+F2 (Krunner)

**Comment by psifidotos** [comment]
Show me

**Comment by trmdi** [comment]
For example, when you click on the "Configure..." button, it will open this window:
![image](https://user-images.githubusercontent.com/11857205/50734040-ee43d680-11ca-11e9-8999-33a6d2ceef97.png)

**Comment by psifidotos** [comment]
I would prefer to open the kcm that you can choose the current window decoration. I don't know how this is achieved though 🙂

**Comment by trmdi** [comment]
After rethinking, I see it's not really needed too. Never mind. :)
