### ISSUE TITLE
BreezeEnhanced MacOS buttons toggle is stuck in the first style until Plasma restarts

### ISSUE THREAD

**Issue by Zren** [psifidotos/applet-window-buttons#3]
Switching from BreezeEnhanced's MacOS buttons mode to the other button style requires restarting plasma. Switching to another style like Breeze and back doesn't fix it either.

![2018-11-05___18-23-04](https://user-images.githubusercontent.com/416367/48033079-e2368c80-e127-11e8-9d80-1fb47cb03703.png)

**Comment by Zren** [comment]
It seems it's `~/.config/breezerc`, sharing the config with other breeze-like decorations.

https://github.com/tsujan/BreezeEnhanced/search?q=breezerc&unscoped_q=breezerc

* https://github.com/tsujan/BreezeEnhanced/blob/4269128339f581392bdfe66bc72fe8c0a2e82871/breezedecoration.cpp#L262
* https://github.com/tsujan/BreezeEnhanced/blob/159012b1afa32515b79ed419b9cd976e9e23303e/breezebutton.cpp#L56
* https://github.com/KDE/kwin/blob/master/decorations/decorationbridge.cpp#L146

Not quite sure if any of those links help.

Note, this also affects toggling the "Draw circle around close button" in the default Breeze theme.

**Comment by Zren** [comment]
So we watch `breezerc` for changes? Sounds good.

**Comment by psifidotos** [comment]
> So we watch breezerc for changes? Sounds good.

in order to update runtime yes...
in reloads also in you change between different plugins e.g. Breeze and BreezeEnhanced
