### ISSUE TITLE
Blacklist Applications

### ISSUE THREAD

**Issue by dboy591** [psifidotos/applet-window-buttons#30]
It would be nice to be able to add applications to a blacklist. Blacklisted apps would not display buttons in the applet.   I'm thinking of GTK apps with CSDs.

**Comment by psifidotos** [comment]
can you demonstrate the issue please?

**Comment by psifidotos** [comment]
From my understanding the reported issue that CSDs with applet window buttons show both window buttons.

But even by disabling the applet window buttons part then the window buttons are still not shown at the correct place.

From my perspective this a CSDs issue to solve... they probably need to provide a way for maximized CSDs to not draw their window buttons...
