### ISSUE TITLE
Fail to build from source on ubuntu 18.04

### ISSUE THREAD

**Issue by VandaLHJ** [psifidotos/applet-window-buttons#31]
I think i have all required libs, but it still don't build. Sadly, there are no 5.13 on Ubuntu 18.04

$ cmake -DCMAKE_INSTALL_PREFIX=/usr .. -Wnodev
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.50.0") 
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Declarative: /usr/lib/x86_64-linux-gnu/cmake/KF5Declarative/KF5DeclarativeConfig.cmake (found version "5.50.0") 
-- Found KF5Plasma: /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.50.0") 
-- Found KF5PlasmaQuick: /usr/lib/x86_64-linux-gnu/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.50.0") 
-- Found KF5: success (found suitable version "5.50.0", minimum required is "5.38.0") found components:  CoreAddons Declarative Plasma PlasmaQuick 
-- Could not set up the appstream test. appstreamcli is missing.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.50.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.50.0") 
-- Found KF5Service: /usr/lib/x86_64-linux-gnu/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.50.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.50.0") 
-- Found KF5: success (found suitable version "5.50.0", minimum required is "5.26.0") found components:  Plasma WindowSystem I18n Service ConfigWidgets 
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/KF5Package/KF5PackageMacros.cmake:71 (message):
  warnings during generation of metainfo for org.kde.windowbuttons: KCatalog
  being used without a Q*Application instance.  Some translations won't work

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/KF5Plasma/KF5PlasmaMacros.cmake:34 (kpackage_install_package)
  CMakeLists.txt:27 (plasma_install_package)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/lech/Dokumenty/Prywatne/applet-window-buttons/build
lech@Lech-Dell-Latitude-E6220:~/Dokumenty/Prywatne/applet-window-buttons/build$ make
Scanning dependencies of target org.kde.windowbuttons-plasmoids-metadata-json
[  5%] Generating org.kde.windowbuttons-plasmoids-metadata.json
About to parse service type file "/usr/share/kservicetypes5/plasma-applet.desktop"
Found property definition "X-Plasma-API" with type "QString"
Found property definition "X-Plasma-RootPath" with type "QString"
Found property definition "X-Plasma-MainScript" with type "QString"
Found property definition "X-Plasma-ContainmentType" with type "QString"
Found property definition "X-Plasma-DropMimeTypes" with type "QStringList"
Found property definition "X-Plasma-DropUrlPatterns" with type "QStringList"
Found property definition "X-Plasma-NotificationArea" with type "QString"
Found property definition "X-Plasma-NotificationAreaCategory" with type "QString"
Found property definition "X-Plasma-DBusActivationService" with type "QString"
Found property definition "X-KDE-ParentApp" with type "QString"
Found property definition "X-Plasma-Provides" with type "QStringList"
Found property definition "X-Plasma-PreloadWeight" with type "int"
Found property definition "X-Plasma-ConfigPlugins" with type "QStringList"
Found property definition "X-Plasma-StandAloneApp" with type "bool"
Found property definition "X-Plasma-RequiredExtensions" with type "QStringList"
Found property definition "NoDisplay" with type "bool"
Unknown property type for key "Keywords" -> falling back to string
Generated  "/home/lech/Dokumenty/Prywatne/applet-window-buttons/build/org.kde.windowbuttons-plasmoids-metadata.json" 

[  5%] Built target org.kde.windowbuttons-plasmoids-metadata-json
Scanning dependencies of target appletdecorationplugin_autogen
[ 11%] Automatic MOC for target appletdecorationplugin
[ 11%] Built target appletdecorationplugin_autogen
Scanning dependencies of target appletdecorationplugin
[ 16%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o
In file included from /home/lech/Dokumenty/Prywatne/applet-window-buttons/libappletdecoration/appletdecorationplugin.cpp:26:0:
/home/lech/Dokumenty/Prywatne/applet-window-buttons/libappletdecoration/previewclient.h:103:10: error: ‘void Decoration::Applet::PreviewClient::requestShowToolTip(const QString&)’ marked ‘override’, but does not override
     void requestShowToolTip(const QString &text) override;
          ^~~~~~~~~~~~~~~~~~
/home/lech/Dokumenty/Prywatne/applet-window-buttons/libappletdecoration/previewclient.h:104:10: error: ‘void Decoration::Applet::PreviewClient::requestHideToolTip()’ marked ‘override’, but does not override
     void requestHideToolTip() override;
          ^~~~~~~~~~~~~~~~~~
libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:62: recipe for target 'libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o' failed
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o] Error 1
CMakeFiles/Makefile2:448: recipe for target 'libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all' failed
make[1]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by psifidotos** [comment]
For plasma 5.12 you need specific sources, you can find the 5.12 specific page at https://store.kde.org/p/1272871/ Files section

**Comment by psifidotos** [comment]
and here you can find a 5.12 specific branch if you want https://github.com/psifidotos/applet-window-buttons/tree/5.12-0.3?files=1

**Comment by VandaLHJ** [comment]
Well, tried to git clone 5.12-master ... Thanks for help, build successfully from 5.12-0.3.
