### ISSUE TITLE
Compile error on OpenSuse

### ISSUE THREAD

**Issue by eogan** [psifidotos/applet-window-buttons#33]
Hello,

I run OpenSuse Leap 15 wit KDE 5.56. I have QT dev packages installed but I get this error:

-- Found KF5: success (found suitable version "5.56.0", minimum required is "5.38.0") found components:  CoreAddons Declarative Plasma PlasmaQuick
-- Could not set up the appstream test. appstreamcli is missing.

**Comment by psifidotos** [comment]
I suppose you are missing appstreamcli... even though the applet does not need it, your distro does
