### ISSUE TITLE
Move maximized application to other screen with "Disable borders for maximized windows" option ticked - bug

### ISSUE THREAD

**Issue by Kazimazi** [psifidotos/applet-window-buttons#34]
What title says makes my moved application black till I'm not resizing it. 
If I have System Settings > Desktop Behaviour > Desktop Effects > Maximise unticked (so maximizing animation turned off) it works as expected.

Specs:
Operating System: Arch Linux 
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2
Kernel Version: 5.0.7-arch1-1-ARCH

**Comment by psifidotos** [comment]
And why this is related to this applet... This sounds as KWin responsibility

**Comment by Kazimazi** [comment]
possibly yes

**Comment by psifidotos** [comment]
upstream... this should be reproduced independent of applet window buttons applet
