### ISSUE TITLE
Join 5.12 and >5.12 versions into one single version

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/applet-window-buttons#36]

**Comment by YamiYukiSenpai** [comment]
So, (for now) if we're using Qt >=5.12, we should be using 5.12 master?

**Comment by psifidotos** [comment]
no this isnt Qt related but plasma related...

For now, if you are using Plasma=5.12 then you need to use applet 5.12-master
If you are using Plasma>=5.13 then you need to use regular applet master

**Comment by YamiYukiSenpai** [comment]
Ok. Thanks.

**Comment by psifidotos** [comment]
done, https://github.com/psifidotos/applet-window-buttons/commit/f4735d383ac4802b18ebb0fba5b0a74e607ba5e7
