### ISSUE TITLE
The button to show on all desktops isn't working

### ISSUE THREAD

**Issue by YamiYukiSenpai** [psifidotos/applet-window-buttons#37]
When I click the button to show the window to all desktops, it doesn't do that, and I had to restore the window to enable it 

Operating System: Kubuntu 19.04
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.2
Kernel Version: 5.0.0-13-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6500 CPU @ 3.20GHz
Memory: 15.6 GiB of RAM

**Comment by psifidotos** [comment]
wayland or X11?

**Comment by YamiYukiSenpai** [comment]
X11

And speaking of Wayland, this doesn't appear in Wayland environment

**Comment by psifidotos** [comment]
> And speaking of Wayland (I'm using that on another device), this doesn't appear in Wayland environment.

what does not appear under wayland?

**Comment by YamiYukiSenpai** [comment]
Oh wait.  Never mind.  I was referring to the App Menu

**Comment by psifidotos** [comment]
>  I was thinking of the App Menu

the window app menu has been disabled for wayland and you should be able to get your menus inside your windows

**Comment by YamiYukiSenpai** [comment]
How come?

**Comment by psifidotos** [comment]
I don't understand the question

**Comment by psifidotos** [comment]
fixed with latest master version

**Comment by YamiYukiSenpai** [comment]
Out of curiosity, are you updating the release page or is the master stable to use?

**Comment by psifidotos** [comment]
Master is general stable... I release when I find free time
