### ISSUE TITLE
[Question] Multiple Displays/Monitors

### ISSUE THREAD

**Issue by navtojchahal** [psifidotos/applet-window-buttons#39]
### Is there a way to have the "Disable borders for maximized windows" option apply only to the primary display?
I currently have an external monitor (primary display) connected to my laptop (secondary display).
I've attached some pictures below of my setup for reference:

Full Screenshot
![Full Screenshot](https://user-images.githubusercontent.com/37762455/57209208-68734480-6f8c-11e9-8fc7-48d0af285347.png)

Display Settings
![Multiple Monitor Setup](https://user-images.githubusercontent.com/37762455/57207811-bb48fe00-6f84-11e9-8594-84a9ffbc2c9d.png)

Window Buttons Settings
![Window Buttons Settings](https://user-images.githubusercontent.com/37762455/57207887-2bf01a80-6f85-11e9-8b6c-44ceb057ab90.png)

**Comment by psifidotos** [comment]
This is not possible because KWin does not support it.
Latte can support this at different layouts, with Latte v0. 8 you can have different BorderLess setting at different Activities but not in different screens of same Activity
