### ISSUE TITLE
Buttons are visible when Plasma Desktop is focused

### ISSUE THREAD

**Issue by Zren** [psifidotos/applet-window-buttons#4]
When not "hiding buttons when not maximized", the buttons are still visible when no window is available.

Not sure if the buttons should hide or be invisible so it still occupies the space.

![2018-11-05___18-29-34](https://user-images.githubusercontent.com/416367/48033311-df886700-e128-11e8-8890-d9ffa2816d83.png)

**Comment by psifidotos** [comment]
> Not sure if the buttons should hide or be invisible so it still occupies the space.

I can understand the point but there is a big problem in case I enable that hiding for default case. When the user will first add the plasmoid and there wont be any window shown which is most of the cases, in that case the buttons wont be shown at all and it will be a lot of confusing.

I dont know if you can propose something that helps for that.

**Comment by trmdi** [comment]
I think users are smart enough too know that what they've installed is a window buttons applet, so they would certainly know that they need open a window to see the buttons.

**Comment by psifidotos** [comment]
let's see that...

**Comment by psifidotos** [comment]
I will point them in this thread when the question arises in reddit...

**Comment by Zren** [comment]
You could hide it only when widgets are locked? So Mutable = visible, UserImmutable = hidden. SystemImmutable = hidden too I guess.

**Comment by psifidotos** [comment]
not gonna work for Latte... because in Latte there is no locked state... i will leave it with this commit for now... and window buttons can be shown when the user is in user configuring state.
