### ISSUE TITLE
Close buttom doesn't show with PyCharm

### ISSUE THREAD

**Issue by luisfelipehsr** [psifidotos/applet-window-buttons#42]
I'm having this weird bug where, if I maximize PyCharm, the close buttom doesn't appear on the widget (as if I didn't add it). The other buttons appear though. It's the only application where this happens for me. 

I'm using latest user edition KDE neon, latest PyCharm and your widget. The widget is being added to an application bar.

**Comment by psifidotos** [comment]
Screenshot and applet settings screenshot please

**Comment by luisfelipehsr** [comment]
It was my fault having an application bar that was too full. Because I'm displaying a lot of stuff and also displaying PyCharm's menu (it's a particularly large menu) the close buttom got kicked to outside the screen. I reduced one of the applets width and everything is nice now.
![bugged](https://user-images.githubusercontent.com/20591416/60857477-1bf0f300-a1e1-11e9-809c-dd2f3b136547.png)
![fixed](https://user-images.githubusercontent.com/20591416/60857479-1dbab680-a1e1-11e9-8ca9-815705a31412.png)

**Comment by psifidotos** [comment]
No prob,

BTW if you were using a Latte panel and Window AppMenu, in that case the window appmenu would give you horizontal scrolling for those menus that overflow
