### ISSUE TITLE
Buttons are not vertically centered at smaller panel heights

### ISSUE THREAD

**Issue by iboyperson** [psifidotos/applet-window-buttons#43]
Panel height 10% on Latte Dock 0.9.0

![image](https://user-images.githubusercontent.com/10000914/62012843-319e6c00-b140-11e9-9861-48894da6e2c8.png)

**Comment by psifidotos** [comment]
Show me a screenshot of your applet settings

**Comment by iboyperson** [comment]
Closing this issue. I changed nothing and yet it is now vertically centered.

**Comment by psifidotos** [comment]
no prob
