### ISSUE TITLE
Assertion error when uri is "org.kde.appletdecoration" not "org.kde.appletsdecoration"

### ISSUE THREAD

**Issue by enriquezmark36** [psifidotos/applet-window-buttons#44]
Hello, 
Being interested in latte-dock, so I decided to give it a spin including the applets on a KDE Neon Testing install. I like it overall though the memory usage seem to grow over time.

This widget compiled successfully but it always crashes the latte-dock when I tried to add it. It does so specifically on this [line](https://github.com/psifidotos/applet-window-buttons/blob/master/libappletdecoration/appletdecorationplugin.cpp#L45).

This line checks if the uri is "org.kde.appletsdecoration" and aborts when if it's not. But on my system, the uri passed is "org.kde.appletdecoration" (note the absence of 's') so the assert triggers hence preventing me from ever adding this widget on a latte-dock. 

The widget does work after commenting out the said line or changing the "org.kde.appletsdecoration" to "org.kde.appletdecoration".

Would changing this line be okay on the long run?

**Comment by psifidotos** [comment]
This is probably a typo bug, I will check it out

**Comment by psifidotos** [comment]
For the high memory usage, Latte is just using 20Mbyte more, comparing with a system that does not use Latte but rather plasma panels with the same applets. It is how qt+qml manages the system memory. If you get Latte memory usage above 500 Mbyte and it does not stop grow, then you have a memory leak, the fault is probably one of your applets. In the past I had such issue with Event Calendar plugin

**Comment by enriquezmark36** [comment]
I'm not sure whether to call it a memory leak or simply just the reflection of using too many applets since I haven't using this long enough. I have yet to check and compare the usage of a default configuration of Latte against configuration I'm using now.

Anyways, thanks for minding the possible typo.

**Comment by brzegorz** [comment]
I experience the same crash with message:

Error loading QML file: file:///usr/local/share/plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: module "org.kde.appletdecoration" is not installed

**Comment by psifidotos** [comment]
You have a faulty appley installation

**Comment by psifidotos** [comment]
applet installation *
