### ISSUE TITLE
Thunderbird titlebar isn't hidden when maximized

### ISSUE THREAD

**Issue by efade** [psifidotos/applet-window-buttons#49]
![Screenshot_20190901_195057-2](https://user-images.githubusercontent.com/22839979/64076846-43050600-ccf4-11e9-8346-1f895571321d.png)

**Comment by psifidotos** [comment]
Are you using Latte or Plasma?

**Comment by psifidotos** [comment]
Latte panel or Plasma panel?

**Comment by efade** [comment]
Forgot to mention. I'm using plasma. Will try using latte after this, and report back.

**Comment by psifidotos** [comment]
Isn't that a Latte dock on the bottom?

**Comment by efade** [comment]
Yeah. But the top panel is plasma. BTW I tried to replace the top panel
with latte, didn't change anything. The title bar is still visible. Seems
unique to Thunderbird.

**Comment by psifidotos** [comment]
When using Latte you can try : https://userbase.kde.org/LatteDock/TipsAndTricks#Can_I_have_different_Borderless_Maximized_windows_options_between_different_layouts.3F

**Comment by psifidotos** [comment]
You mean that for all other apps is working fine but Thunderbird does not respect it?

**Comment by efade** [comment]
Yup. Firefox and Gimp are fine.

**Comment by psifidotos** [comment]
KWin handles the bordless windows only way this could be possible is by having forced titlebars for Thunderbird. Try to right click the Thunderbird titlebars and check the application and Window settings
