### ISSUE TITLE
[Question] Could the window buttons intergrate with the window title applet?

### ISSUE THREAD

**Issue by blueuser2** [psifidotos/applet-window-buttons#51]
With the window title and window appmenu applets, I can hide the appmenu until I hover over the window title. Could this also be implemented for the window buttons?

**Comment by psifidotos** [comment]
You mean to hide also the buttons until the mouse is hovering the window title?

**Comment by blueuser2** [comment]
Exactly this. That way only the title could be displayed until I hoover over it, replacing it with the buttons and appmenu.

**Comment by ChrisP4** [comment]
I came here meaning to ask for the same thing! 

It's not a huge issue, it's not even a minor one really, more like a mild preference.

**Comment by psifidotos** [comment]
it is possible but that would mean that three different applets should communicate with each other in a sensible way. It is ifeasible but I am going to leave for the far end of the development, after all other improvements have been landed and as long it does not break the Window Applet(s) experience

**Comment by kupiqu** [comment]
> Exactly this. That way only the title could be displayed until I hoover over it, replacing it with the buttons and appmenu.

That is an interesting option. If that would be implemented, I might configure the title applet to show the entire window title (app - title) instead of just the appname.

However, window title imo should be replaced in space only by appmenu, or at least have an option to do it this way.

I know you're not going to implement this tomorrow, but saying this for the record because some users keep title and appmenu on the left and buttons on the right, as it is by default in kde window decorations. Hence, it seems impossible to access buttons if they appear only while hovering window title, as they appear on the other end.

**Comment by psifidotos** [comment]
Actually I am not going to implement it... I am totally uninterested in this... if applets can communicate with each other like Window Title and Window AppMenu are doing in Latte v0.9.x then ok but merging the applets from my side, is not of my interests

**Comment by kupiqu** [comment]
> Actually I am not going to implement it...

That is totally fine to me. I was just trying to mention that this may seem less easy than it seems in some configurations such as mine (and possibly some others)

> if applets can communicate with each other like Window Title and Window AppMenu are doing in Latte v0.9.x then ok

Could you please develop what you mean?

**Comment by psifidotos** [comment]
> Could you please develop what you mean?

When Window Title and AppMenu are used in Latte v0.9.x they both provide a Unity mode meaning that the appmenu can be totally hidden until the Window title is hovered. This is achieved by communicating Window Title with AppMenu by using Latte as a bridge to do so...

**Comment by psifidotos** [comment]
so in other words, I can think of supporting this but only through Latte Applets Communication mechanisms...

**Comment by kupiqu** [comment]
I see, so I can do this already:

> I might configure the title applet to show the entire window title (app - title) instead of just the appname.

I tested and works, cool stuff! :)

**Comment by kupiqu** [comment]
> I tested and works, cool stuff! :)

The only minor issue I see is that I am not able to easily configure the title applet anymore (one needs to do it by entering latte settings first, so the applet is accessible)
