### ISSUE TITLE
Change to small resolution get a size problem

### ISSUE THREAD

**Issue by buntupana** [psifidotos/applet-window-buttons#52]
I have a 2560x1440(QHD) resolution monitor, when I switch to a 1920x1080(FHD) TV, the size of the icons are way bigger and the margins does not match properly with the panel. I'm using a scaling factor of 1.4

- **QHD resolution:**

![scaling_0](https://user-images.githubusercontent.com/13851235/65765433-86526900-e128-11e9-8645-4cf9f76ccaee.png)

- **FHD resolution:**

![image](https://user-images.githubusercontent.com/13851235/65765589-f7921c00-e128-11e9-97a9-3af8cb59914a.png)

- **Windows Buttons Applet settings:**

![image](https://user-images.githubusercontent.com/13851235/65765868-a898b680-e129-11e9-9b78-079d5ecec51b.png)

- **Latte dock panel size settings:**

![image](https://user-images.githubusercontent.com/13851235/65765978-e990cb00-e129-11e9-914e-bb18d5cc3361.png)

**Comment by psifidotos** [comment]
1. If you close Latte and restart it the problem remains?
2. If you make the thickness margin 0px. the problem remains after you restart Latte?

**Comment by buntupana** [comment]
**1.- If you close Latte and restart it the problem remains?**

![scaling_2](https://user-images.githubusercontent.com/13851235/65779003-3636cf00-e147-11e9-9f8f-2bd72208659c.png)

Restarting solve the problem partially because the applet is keeping the pixel margins with the new resolution and it makes the buttons too small.

**2.- If you make the thickness margin 0px. the problem remains after you restart Latte?**

![scaling_3](https://user-images.githubusercontent.com/13851235/65779017-40f16400-e147-11e9-81e3-9dbb97bf8a08.png)

**Comment by psifidotos** [comment]
Ok so this is not applet fault. The applet does not paint the buttons, the buttons are painted from each decoration used, the applet just provides the space in which the buttons must be painted. In your case the decoration used is Breeze, so I believe something breaks with Breeze.

I will leave it open in case any more findings are found.

**Comment by buntupana** [comment]
It would be really nice to have a relative size for the margins like in latte dock, in that way if I change resolution the buttons will have the same size. Or mabye have to option to have the buttons with the same size that we have in the window (I don't know if this is possible to implement)

**Comment by psifidotos** [comment]
Having relative icon size based on the panel thickness it is possible, but that wouldn't solve the mentioned issue. 

Having an option for the same size with the window decoration is not possible because decorations do not expose that.

**Comment by buntupana** [comment]
it wouldn't solve the issue but at least it will have the same size after restart latte dock :)

**Comment by psifidotos** [comment]
try latest master... I introduced a button size percentage and at the same time checked out its behaviour when changing screen resolutions, it worked without issues...

![image](https://user-images.githubusercontent.com/2216474/65789468-2084d200-e166-11e9-8175-4b94165eacd0.png)

**Comment by buntupana** [comment]
Cool, it works. Thank you so much. Btw, which decoration do you use?

**Comment by psifidotos** [comment]
Breeze

**Comment by psifidotos** [comment]
I use Opensuse Tumbleweed
