### ISSUE TITLE
Applet window buttons on openSUSE Leap 15.1

### ISSUE THREAD

**Issue by rifkiaz** [psifidotos/applet-window-buttons#55]
why window buttons can't install on openSUSE Leap 15.1?

**Comment by psifidotos** [comment]
Says who?

**Comment by rifkiaz** [comment]
oh i'm sorry, i forget to attach picture.
see my attach picture, when i install applet window button on my machine running with openSUSE Leap 15.1. my question, how to fix it? 
![Screenshot_20191014_233251-1](https://user-images.githubusercontent.com/23344569/66767820-70d88f80-eedb-11e9-9fb6-709cb9100354.png)

**Comment by psifidotos** [comment]
you are missing development package for kf5 declarative
