### ISSUE TITLE
[Feature] Hide title bar when window is maximized

### ISSUE THREAD

**Issue by Abuelodelanada** [psifidotos/applet-window-buttons#57]
It'd be nice to have the option of hiding the title bar of the window when it's maximized.

This feature is present in [plasma-applet-active-window-control](https://github.com/kotelnik/plasma-applet-active-window-control):

![imagen](https://user-images.githubusercontent.com/939888/67207154-5b86c800-f3e9-11e9-84a6-d6c655dccdd4.png)

With out this feature we have a lot us useless space:

![imagen](https://user-images.githubusercontent.com/939888/67206393-f088c180-f3e7-11e9-955a-065ea158dfec.png)

**Comment by blueuser2** [comment]
I assume your also using latte-dock. If you go into layouts there should be a column called borderless where you can tick it for your layout. This will remove the title bar for maximized windows.
If you aren't using latte dock then you should have the option in the applet's settings window.

**Comment by Abuelodelanada** [comment]
Thank you very much @blueuser2

**Comment by srvanrell** [comment]
Can you help me to hide tittlebar on maximized windows? Where is the option? I coudln't find it

I have Kubuntu 20.04 and Plasma 5.18.5

Thanks in advance

**Comment by psifidotos** [comment]
Are you using Latte or plasma panel?

**Comment by srvanrell** [comment]
I'm using plasma panel. Is it possible to hide title bars using plasma
panel?

**Comment by psifidotos** [comment]
https://askubuntu.com/questions/253337/remove-title-bar-and-borders-on-maximized-windows-in-kubuntu

**Comment by srvanrell** [comment]
Thank you @psifidotos !! 

Sorry to bother you with such stupid question. I was not able to perform the right question to google.
