### ISSUE TITLE
Being able to specify the exact ButtonHeight and ButtonWidth

### ISSUE THREAD

**Issue by Kodehawa** [psifidotos/applet-window-buttons#59]
Title. Sometimes some themes can't integrate well with the window buttons applet because the size is just *not quite right*, being able to specify them manually would be a huge addition.
It's obviously possible to do this on the aurorae theme as per this screenshot, which is what I'd like to accomplish with the window button applet.
![image](https://user-images.githubusercontent.com/20606963/68345469-290ae980-00d0-11ea-8d6c-faa7660dc45c.png) 

This is because without fine-tuning, some buttons always look blurry (I'm looking at you, qogir-dark-circle)
example: 
![image](https://user-images.githubusercontent.com/20606963/68345767-eb5a9080-00d0-11ea-9a62-6c11b1c93f1a.png)

**Comment by psifidotos** [comment]
Enable the Metrics, Use from decoration if any are found. It finds what is the ratio between button width and height and applies it

**Comment by Kodehawa** [comment]
It's still blurry like that with this specific window decoration :(

**Comment by psifidotos** [comment]
1. So with latest master do not enable the metrics calculations.
2. After you install window buttons again, run latte from terminal with: `latte-dock -d`
3. after [2] when you change the buttons size percentage in the terminal there will be a message showing how much is the button thickness calculated. Setup the percentage in a value that gives you button thickness of 23px.

**Comment by Kodehawa** [comment]
Thanks :)

**Comment by Kodehawa** [comment]
84% gives me a button thickness of 22 and and 85% gives me a button thickness of 24... 
![image](https://user-images.githubusercontent.com/20606963/68410103-f06a1f00-0166-11ea-87d7-7407b63f3004.png)

**Comment by psifidotos** [comment]
you need to adjust the Latte Applets size.... increase or reduce it by 1px.

**Comment by Kodehawa** [comment]
Yep. Setting it at 25px did the trick, thanks you :dagger: 
sorry for the issues :(
