### ISSUE TITLE
Improve multi-screen behavior

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/applet-window-buttons#6]
In my opinion the best multi-screen behavior is the following:

**State: Default**

- When in the plasmoid screen there is no window showing the buttons are **NOT** shown
- When in the plasmoid screen there are windows none of whom is active the buttons are **NOT** shown
- When in the plasmoid screen there is an active window the buttons are shown just fine

**State: Show only for active+maximized windows**

- When in the plasmoid screen there is no window showing the buttons are **NOT** shown
- When in the plasmoid screen there are windows none of whom is active the buttons are **NOT** shown
- When in the plasmoid screen there is an active window which is not maximized the buttons are  **NOT** shown
- When in the plasmoid screen there is an active window which is also maximized the buttons are shown just fine

**Comment by psifidotos** [comment]
I checked it out and this is the current behavior in multi-screen but I will leave it open in case there is more user feedback

**Comment by rokups** [comment]
Just tested. This works pretty good. What do you think if buttons were visible and controlled last active application on particular screen? If `plasma-active-application` applet did the same it would give an illusion of perfectly merged titlebar into a panel.

**Comment by psifidotos** [comment]
> What do you think if buttons were visible and controlled last active application on particular screen?

unfortunately I wouldnt support that except if Global menu could do it also and I dont think this could be possible... it needs investigation... In other words concerning this it will totally depend on Global Menu support... if Global menu becomes multi-screen aware and hides when there is no active window in that screen the two other applets should do the following...
