### ISSUE TITLE
Window Button Applet and multiple screens

### ISSUE THREAD

**Issue by g0r3** [psifidotos/applet-window-buttons#60]
Hi,

I am using Window Button Applet (and Window Button Title) since quite some while and I'm super happy with it. But today I noticed some little issues when you use them the first time on a system with multiple screens. 

There I have the problem, that when setting up the applets for each screen, and you click on a window on a different screen, they still will react on the window losing the focus on the current screen and hide the buttons and the title, since there is no more active window on the current screen. 

A imho better solution would be, that the applets memorize the last application for the current screen and continue to display the window buttons and tiles until the active application for this screen changes. I hope I made clear what I mean. Otherwise just ask - I'll happily try to deliver a better explanation :)

**Comment by psifidotos** [comment]
1. Are you using them in Plasma or Latte? 
2. They both have an option for this, don't they?

**Comment by g0r3** [comment]
To 1.: I am using them in Plasma in a top side panel. The window button applet is only shown if the application is maximized. When maximized I hide the window borders. 

To 2.: Yes, they have this option, but the option doesn't solve my problem. I'm not sure if you have a second display to reproduce it but I will list all the steps you have to do tho reproduce the issue:

1. Set up two panels, one on each screen, each panel having the Window Button and Window Title Applet attached to them. Turn the "only current screen" option on for both.
2. Open an arbitrary application with application menu on screen one and maximize it. (In order to see the window buttons)
3. Open another app on the second screen. Maximize it too.

Now you have the situation, that each panel shows the window buttons, title and gobal menu of the active/maximized window on the current screen. But when you activate the application window on the other screen (without moving it to another) all the applets on the first screen will vanish, because there is now active window there. Imho it would be a better approach to save and show the last active window buttons/global menu/title per screen until it changes.

This problem only appears with multiple screens (otherwise the applets works perfectly fine) and is a little bit annoying because you only can see the elements window buttons/menu when the window on the current screen is active. So if you are working on screen one and you want to close the maximized program on screen two, you first have to make the application active by clicking it and just then you will be able to see the global menu and window button.

I hope this makes it more clearly what I mean.

Thank you

**Comment by psifidotos** [comment]
Ok, now I understand... this is a plasma limitation... Tracking the last active window at per applet basis is not of a per applet responsibility. If you recreate your panels with Latte panels from Latte v0.9.x then this is solved. Latte is tracking last active window at per panel basis, and that of course means and at per screen one. Latte is taking all the burden for this and provides these information to applets to use. Window Buttons/Title/AppMenu are already supporting this. That would also mean that you can also have different global menus at different screens with the Latte combo...

**Comment by g0r3** [comment]
Thank you. I will try that out and report back.

**Comment by psifidotos** [comment]
btw out of curiousity are you using master version of the plasmoid? The palsmoid in the master version provides an option called: **Show: At least one window is shown** which is also enabled for plasma panels. Try that first if you dont want to check out Latte.

**Comment by g0r3** [comment]
Hi,

using Latte panels seem to solve this problem. Some questions though: How to control the size in the latte panel? My title widget now reaches far towards the mid of the screen. And also my logoff/power  button is placed vertical because of space and i have no clue how to give it more. Also the Desktop doesn't seem to adjust for the latte panel, unlike as for the KDE panel, meaning that desktop icons partly are hidden by the panel

![image](https://user-images.githubusercontent.com/3685646/69360308-9d29bd80-0c8a-11ea-95c0-ec7d062dad50.png)

**Comment by psifidotos** [comment]
1. have you set alignment: Justify ?
2. the desktop icons is a plasma issue/limitation and I publish an article how this can be solved/workaround with plasma >= 5.17.3

**Comment by g0r3** [comment]
Yes, I am using the Justify setting

**Comment by psifidotos** [comment]
Which one is your title widget? I can guarantee only Window Title... For lock widget etc this is plasma widget, so ask for at plasma devs. The thickness of the Latte panel is at: Appearance, Items size

**Comment by g0r3** [comment]
The Title, Window Button and AppMenu are from you. And I understand that you cannot guarantee the functionality of other items. But imho the issue here is not the widget itself but that I seem cannot resize/move them in any way if they are within a Latte panel. I also have the problem on the other side with the tile applet, which for some reason reaches far into the mid of the screen, even if the name is much shorter and there is nothing else in the panel on the left side of the widget.

**Comment by g0r3** [comment]
Here is my config file. Maybe you can see something in it:

```ruby
[ActionPlugins][1]
RightButton;NoModifier=org.kde.latte.contextmenu

[Containments][1]
activityId=
byPassWM=false
dockWindowBehavior=true
enableKWinEdges=true
formfactor=2
immutability=1
isPreferredForShortcuts=false
lastScreen=-1
location=3
onPrimary=true
plugin=org.kde.latte.containment
raiseOnActivityChange=false
raiseOnDesktopChange=false
settingsComplexity=4
timerHide=700
timerShow=200
viewType=1
visibility=0
wallpaperplugin=org.kde.image

[Containments][1][Applets][5]
immutability=1
plugin=org.kde.plasma.systemtray

[Containments][1][Applets][5][Configuration]
PreloadWeight=15
SystrayContainmentId=6

[Containments][1][Applets][60]
immutability=1
plugin=org.kde.windowappmenu

[Containments][1][Applets][60][Configuration]
PreloadWeight=18

[Containments][1][Applets][60][Configuration][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][Applets][60][Configuration][General]
containmentType=Latte
fillWidth=true
filterByScreen=true
filterChildrenWindows=true

[Containments][1][Applets][61]
immutability=1
plugin=org.kde.windowbuttons

[Containments][1][Applets][61][Configuration]
PreloadWeight=23

[Containments][1][Applets][61][Configuration][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][Applets][61][Configuration][General]
buttons=5|3|4|10|2|9
containmentType=Latte
slideAnimation=true
visibility=ActiveMaximizedWindow

[Containments][1][Applets][64]
immutability=1
plugin=org.kde.plasma.lock_logout

[Containments][1][Applets][64][Configuration]
PreloadWeight=18

[Containments][1][Applets][64][Configuration][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][Applets][65]
immutability=1
plugin=org.kde.plasma.digitalclock

[Containments][1][Applets][65][Configuration]
PreloadWeight=38

[Containments][1][Applets][65][Configuration][Appearance]
showDate=true

[Containments][1][Applets][65][Configuration][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][1][ConfigDialog]
DialogHeight=1338
DialogWidth=539

[Containments][1][Configuration]
PreloadWeight=10
byPassWM=false
isPreferredForShortcuts=false
onPrimary=true
viewType=1

[Containments][1][General]
advanced=false
animationLauncherBouncing=false
animationWindowAddedInGroup=false
animationWindowInAttention=false
appletOrder=61;60;5;65;64
autoDecreaseIconSize=false
dragActiveWindowEnabled=true
iconMargin=0
iconSize=24
panelPosition=10
panelSize=100
plasmaBackgroundForPopups=true
shadowOpacity=35
shadowSize=45
shadows=None
showGlow=false
shrinkThickMargins=true
splitterPosition=1
splitterPosition2=3
thickMargin=0
titleTooltips=false
zoomLevel=0

[Containments][1][Indicator]
customType=
enabled=true
enabledForApplets=true
padding=0.07999999821186066
type=org.kde.latte.default

[Containments][6]
PreloadWeight=10
activityId=
formfactor=2
immutability=1
lastScreen=-1
location=3
plugin=org.kde.plasma.private.systemtray
wallpaperplugin=org.kde.image

[Containments][6][Applets][10]
immutability=1
plugin=org.kde.plasma.devicenotifier

[Containments][6][Applets][10][Configuration]
PreloadWeight=10

[Containments][6][Applets][11]
immutability=1
plugin=org.kde.plasma.notifications

[Containments][6][Applets][11][Configuration]
PreloadWeight=10

[Containments][6][Applets][13]
immutability=1
plugin=org.kde.plasma.clipboard

[Containments][6][Applets][13][Configuration]
PreloadWeight=10

[Containments][6][Applets][16]
immutability=1
plugin=org.kde.plasma.networkmanagement

[Containments][6][Applets][16][Configuration]
PreloadWeight=10

[Containments][6][Applets][58]
immutability=1
plugin=org.kde.plasma.keyboardindicator

[Containments][6][Applets][58][Configuration]
PreloadWeight=10

[Containments][6][Applets][59]
immutability=1
plugin=org.kde.plasma.vault

[Containments][6][Applets][59][Configuration]
PreloadWeight=10

[Containments][6][Applets][9]
immutability=1
plugin=org.kde.plasma.volume

[Containments][6][Applets][9][Configuration]
PreloadWeight=10

[Containments][6][ConfigDialog]
DialogHeight=540
DialogWidth=720

[Containments][6][General]
extraItems=org.kde.plasma.networkmanagement,org.kde.ktp-contactlist,org.kde.plasma.clipboard,org.kde.plasma.printmanager,org.kde.kdeconnect,org.kde.plasma.pkupdates,org.kde.plasma.bluetooth,org.kde.plasma.notifications,org.kde.plasma.devicenotifier,org.kde.plasma.volume,org.kde.plasma.mediacontroller,org.kde.discovernotifier,org.kde.plasma.keyboardindicator,org.kde.plasma.vault
knownItems=org.kde.plasma.networkmanagement,org.kde.ktp-contactlist,org.kde.plasma.clipboard,org.kde.plasma.printmanager,org.kde.kdeconnect,org.kde.plasma.pkupdates,org.kde.plasma.battery,org.kde.plasma.bluetooth,org.kde.plasma.notifications,org.kde.plasma.devicenotifier,org.kde.plasma.volume,org.kde.plasma.mediacontroller,org.kde.discovernotifier,org.kde.plasma.keyboardindicator,org.kde.plasma.vault
showAllItems=true

[LayoutSettings]
activities=
background=
color=lightskyblue
globalLaunchers=
lastUsedActivity=94eac9b2-5f5e-492c-9b1a-7157584d75ce
launchers=
preferredForShortcutsTouched=false
showInMenu=true
textColor=fcfcfc
version=2

```

**Comment by g0r3** [comment]
Ok, I think I have figured it out now:
You can place widgets in three areas in the panel: left, mid and right. When you drag a new widget out of the widget list, the latte panel presents you the circle with the blue plus sign to place the widget. This works fine, if it is the first widget or if there are still other widgets left. But if I remove the last widget on one side, the panel doesn't present me the plus sign anymore. So I was dropping them mid without realizing what was happening, because it was the only plus sign that Latte presented to me.

I've recreated now the panel, repopulated it with the widgets and now everything seems to work properly. Thanks for your help, your awesome applets and keep up the good work!

**Comment by psifidotos** [comment]
It takes a little to figure out Latte way but in the end it is pretty straightforward
