### ISSUE TITLE
PPA is now working

### ISSUE THREAD

**Issue by krisives** [psifidotos/applet-window-buttons#61]
In the past I had contacted you about trying to package this for Ubuntu based systems such as KDE Neon but I had some trouble. After debugging the build scripts on Launchpad it's now working and will automatically rebuild this repository daily via this recipe:

https://code.launchpad.net/~krisives/+recipe/applet-window-buttons-daily

Packages are put into this PPA:

https://code.launchpad.net/~krisives/+archive/ubuntu/applet-window-buttons

Dependencies, package name, copyright, etc. are defined via this repository:

https://code.launchpad.net/~krisives/+archive/ubuntu/applet-window-buttons

Steps to install on any modern Ubuntu system are:

    sudo add-apt-repository ppa:krisives/applet-window-buttons
    sudo apt install applet-window-buttons

If you want to add these to the `README.md` or `INSTALLATION.md` file feel free to. You're also free to copy the recipe or I can transfer ownership of that `applet-window-buttons` project on Launchpad to you if you want. I would have made a PR and modified the files myself but in the past my PRs for that have been rejected because you have your own rules on where things should go.

Cheers!

**Comment by psifidotos** [comment]
Really nice!

Actually packaging is totally out of my interests. Best way to inform users is through INSTALLATION.MD file which is totally community driven, that applies to all of my projects, including Latte. Can you please make a PR and update INSTALLATION. MD with a new section?

**Comment by krisives** [comment]
PR is #62

**Comment by psifidotos** [comment]
done...

**Comment by ngirard** [comment]
Hey @krisives, thanks for your efforts !

Would you mind adding Ubuntu 20.10 to your PPA ?

Cheers !

**Comment by krisives** [comment]
I have added the new PPA release targets.

**Comment by ngirard** [comment]
@krisives, thanks & happy new year !
