### ISSUE TITLE
[Feature request] Use a shared decoration for all buttons

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-buttons#63]
Currently each button is created with a new decoration. It's not optimized because all buttons could belong to only a shared decoration.
This also let buttons communicate to each other through that shared decoration.

**Comment by psifidotos** [comment]
ok, I managed to do this... even though it was not just straight forward and it can create some functionality breakage so it needs debugging...

**Comment by psifidotos** [comment]
@trmdi you can test it out if you want...

**Comment by trmdi** [comment]
Thank you. It works perfectly now. :)

**Comment by psifidotos** [comment]
> Thank you. It works perfectly now. :)

nice! :) this a big change, so if something breaks, please report back...
