### ISSUE TITLE
The applet doesn't work 100% identically compared to the buttons on a normal window

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-buttons#64]
I found this from this patch: https://github.com/kupiqu/SierraBreezeEnhanced/pull/56
It still works correctly with normal KWin windows as well as the preview window in SystemSettings.

**Comment by trmdi** [comment]
Just curious, why isn't this class derived from `KDecoration2::Decoration`?
https://github.com/psifidotos/applet-window-buttons/blob/14094d6c9ec4f1e0724d96ab46761b59951adcca/libappletdecoration/previewshareddecoration.h#L42

**Comment by trmdi** [comment]
Can the `SharedDecoration` class be derived from `KDecoration2::Decoration` ?

**Comment by kupiqu** [comment]
Interestingly enough, it worked for me until I restarted latte (including the update to kupiqu/SierraBreezeEnhanced#56). 

Perhaps some heuristic failed?

**Comment by psifidotos** [comment]
The window buttons applet is a different case than the decorations preview kcm. So @trmdi you must describe me what your code is doing and I can tell you afterwards what is happening. I have not found any way to draw real deoration2 in the applet. It is not possible because a real decoration draws also the window title background.

**Comment by trmdi** [comment]
I just override the virtual function in the Decoration class.
https://github.com/kupiqu/SierraBreezeEnhanced/blob/2ea6819f8512dbd7b8902a24b26d8ec80b1d30f8/breezedecoration.cpp#L360

**Comment by psifidotos** [comment]
I don't think that can work with the applet

**Comment by trmdi** [comment]
> I don't think that can work with the applet

Can we create a decoration like this: https://github.com/KDE/kwin/blob/44f6b702458598f14f6ac1c836d7ba3093d203e5/kcmkwin/kwindecoration/declarative-plugin/previewitem.cpp#L81(1)

And create buttons derived from KDecoration2::Button. (2)
According to this: https://github.com/KDE/kdecoration/blob/771ed0c4f8c21674ec558102001507bc9bbde3d0/src/decoration.h#L237
Our butons (2) would have access to KDecoration2::Decoration's `d` private member.

Then we can use `d`  to get all buttons of (1) with: d->buttons ? (3)
https://github.com/KDE/kdecoration/blob/771ed0c4f8c21674ec558102001507bc9bbde3d0/src/decoration_p.h#L65

We could:
- forward the mouse event to the decoration in (1)
- use the paint button of buttons in (3)

**Comment by psifidotos** [comment]
@trmdi please test again with latest master, there is a chance that https://github.com/psifidotos/applet-window-buttons/commit/d7b466ec9952c9b26dd858a8a428adaedfcf8425 has fixed this

**Comment by trmdi** [comment]
Maybe, I'm about to tell you that when debugging I found that all buttons created by the applet has the same decoration which is a Breeze::Decoration object.

**Comment by trmdi** [comment]
Didn't work.

**Comment by psifidotos** [comment]
https://github.com/psifidotos/applet-window-buttons/blob/master/libappletdecoration/previewbutton.cpp#L502

It should, shouldn't it?

**Comment by trmdi** [comment]
I don't know, I try adding a `qDebug() << event->posF` [here](https://github.com/kupiqu/SierraBreezeEnhanced/blob/master/breezedecoration.cpp#L373) and it doesn't show changes when moving mouse on the applet.

**Comment by psifidotos** [comment]
me neither, it should just work like all the rest signals

**Comment by trmdi** [comment]
Ah, it is the value of "e " which you send to decoration() is not true.

**Comment by psifidotos** [comment]
how about:
```

void PreviewButtonItem::hoverMoveEvent(QHoverEvent *event)
{
    if (!m_button) {
        return;
    }

    QPoint newPos (qBound((double)m_visualGeometry.left(), m_visualGeometry.left() + event->posF().x(), (double)m_visualGeometry.right()),
                   qBound((double)m_visualGeometry.top(), m_visualGeometry.top() + event->posF().x(), (double)m_visualGeometry.bottom()));

    QPoint oldPos (qBound((double)m_visualGeometry.left(), m_visualGeometry.left() + event->oldPosF().x(), (double)m_visualGeometry.right()),
                   qBound((double)m_visualGeometry.top(), m_visualGeometry.top() + event->oldPosF().x(), (double)m_visualGeometry.bottom()));

    //! this a workaround in order to send proper coordinates
    //! that confirm the button visual coordinates
    QHoverEvent e(event->type(),
                  newPos,
                  oldPos,
                  event->modifiers());

    QCoreApplication::instance()->sendEvent(decoration(), &e);
}
```

**Comment by trmdi** [comment]
not work.

**Comment by trmdi** [comment]
Hmm, the problem is the geometry and layout are very different between the applet and the normal Decoration. So we can't send a right event to the decoration.
Could you just send the event to PreviewButton instead of to the Decoration like before? And set the objectName of m_decoration is "applet-window-buttons" in order for me to workaround this case in SierraBreezeEnhanced using the decoration's signal instead.

**Comment by psifidotos** [comment]
Send me a PR with what you are describing in order to test it out

**Comment by trmdi** [comment]
I don't know, but apply those 2 patches I've just sent fix all issues.

**Comment by psifidotos** [comment]
@trmdi do you still want https://github.com/psifidotos/applet-window-buttons/commit/d7b466ec9952c9b26dd858a8a428adaedfcf8425 to stay in master or I can revert it?

**Comment by kupiqu** [comment]
As far as I can see, kupiqu/SierraBreezeEnhanced#58 only affects  the window buttons applet and depends on #68 to be merged here. So before I merge kupiqu/SierraBreezeEnhanced#58 I would like to know if you are planning to merge #68. Thank you

**Comment by psifidotos** [comment]
@kupiqu I will merge it but I am waiting for a response from @trmdi

**Comment by trmdi** [comment]
https://github.com/psifidotos/applet-window-buttons/commit/d7b466ec9952c9b26dd858a8a428adaedfcf8425 is still ok for me. Can you confirm it @kupiqu ?

**Comment by kupiqu** [comment]
> [d7b466e](https://github.com/psifidotos/applet-window-buttons/commit/d7b466ec9952c9b26dd858a8a428adaedfcf8425) is still ok for me. Can you confirm it @kupiqu ?

I think what @psifidotos needs to know (correct me if wrong) is if #68 builds on top of d7b466e or if it is independent, so it can be reverted.

As I didn't test #68, neither kupiqu/SierraBreezeEnhanced#58 I cannot really answer that question...
