### ISSUE TITLE
Suggestions for a better handling of maximized windows

### ISSUE THREAD

**Issue by g0r3** [psifidotos/applet-window-buttons#65]
Hi,

I have two suggestions, that in my opinion would improve the logic behind the window buttons.

**First:**
while using the window button applet I noticed, that KWin offers different types for maximizing windows ("maximize", "maximize vertically/horizontally", while window button applet all treats them as the same. This can result in the window buttons being visible, if the window where they belong to, technically is not maximized and also the regular window buttons in the title bar of the window are still visible

To reproduce:
1. Set Window Buttons to "Active Window is maximized"
2. Goto System Settings/Shortcuts/KWin and assign a shortcut to either the "Maximize Window Vertically/Horizontally"
3. Activate a non maximized window and use the shortcut
4. You now should see the Window Button applet, even though the window is not really "maximized"

**Second:**
This behavior I noticed on my multi screen setup. In the Window button menu I have set the "Active window is maximized" option. This works fine while you have only one screen. But if you have multiple screens, you will have the problems, that if you have two maximized windows, one on each screen, and you change the active maximized window, the window buttons on the other screen will disappear (because no window on this screen active anymore). I think I already pointed out something similar in an earlier issue opened by me, where you suggested to switch to a latte panel (which I am still using). The better way would imho be to keep showing the window buttons for the *last* active maximized window for each screen.

**Comment by psifidotos** [comment]
First: I am not interested in it
Second: if you use Latte v0.9 isn't that's happening?

**Comment by g0r3** [comment]
> First: I am not interested in it
Maybe others? I am very certain that the vast majority doesn't associate anything else as maximized than a window using the whole screen. I actually considered this a bug in the applet until I realized whats going on, since you can invoke this vertically/horizontally maximized window state by accident just with the mouse and without the use of hotkeys.

> Second: if you use Latte v0.9 isn't that's happening?
I'm using Latte 9.4

**Comment by psifidotos** [comment]
Split the thread in two different threads and provide screenshots with explanation for the first issue. The second issue I think is easily fixable with Latte case but open a thread to track it.
