### ISSUE TITLE
Suggestion: Allow vertical/horizontal Maximize to be handled different than regular Maximize

### ISSUE THREAD

**Issue by g0r3** [psifidotos/applet-window-buttons#66]
While using the window button applet I noticed, that KWin offers different types for maximizing windows ("maximize", "maximize vertically/horizontally", while window button applet all treats them as the same. This can result in the window buttons being visible, if the window where they belong to, technically is not maximized and also the regular window buttons in the title bar of the window are still visible.

To reproduce:

Set Window Buttons to "Active Window is maximized"
Goto System Settings/Shortcuts/KWin and assign a shortcut to either the "Maximize Window Vertically/Horizontally"
Activate a non maximized window and use the shortcut
You now should see the Window Button applet, even though the window is not really "maximized"

I'd like to propose an option to not show Window Buttons for vertical/horizontal Maximize since this behavior imho is quite weird

**Comment by psifidotos** [comment]
This should have been the default behavior, if you use plasma panel and add window buttons in it, do you have that issue?

This is probably Latte fault

**Comment by psifidotos** [comment]
this is fixed in Latte with: https://phabricator.kde.org/R878:7c77270f0b666ef7f5082ab46415da52dda778f4

upcoming Latte v0.9.6
