### ISSUE TITLE
Something is wrong with the show/hide state

### ISSUE THREAD

**Issue by trmdi** [psifidotos/applet-window-buttons#69]
As you see in the screenshot, I choose "Last active window is maximized" for the Show option, but why does it still display when the last active is not maximized?

![image](https://user-images.githubusercontent.com/11857205/70683180-e0001380-1cd3-11ea-81ad-3490d0f0aa1d.png)

![image](https://user-images.githubusercontent.com/11857205/70683337-a11e8d80-1cd4-11ea-83c4-7062ba479a24.png)

**Comment by psifidotos** [comment]
Because  you are configuring the applet in such state the buttons are always visible

**Comment by trmdi** [comment]
Ah, it could be the buttons of another window, not the current active window.
Then can the title widget and the appmenu widget follow this behavior? Just a question, I haven't checked their available options yet.

**Comment by psifidotos** [comment]
As long as an applet is showing its settings or we are in edit mode, all hiding features are disabled for window applets

**Comment by trmdi** [comment]
> As long as an applet is showing its settings or we are in edit mode, all hiding features are disabled for window applets

Yes, I've just realized this. I was a bit confused because that is also a window. So I think there should be a text like "(Do not apply tto this window)".

**Comment by trmdi** [comment]
Another thing I want to discuss is that, these 3 applets have different views about the "Plasma desktop":
- applet-window-buttons: does not consider it is a window.
- applet-window-title/appmenu: consider it as a window.

When you have only one maximized window, then you minimize this window, this thing will happens:
![screenshot](https://user-images.githubusercontent.com/11857205/70683337-a11e8d80-1cd4-11ea-83c4-7062ba479a24.png)

**Comment by psifidotos** [comment]
Last maximized window option for window buttons does not ignore the minimized case?

**Comment by trmdi** [comment]
> Last maximized window option for window buttons does not ignore the minimized case?

Yes, it is.

**Comment by psifidotos** [comment]
> > Last maximized window option for window buttons does not ignore the minimized case?
> 
> No, it doesn't ignore that case.

ok fixed in master

**Comment by trmdi** [comment]
Thank you!
