### ISSUE TITLE
Applet creates a lot of inotify watchers 

### ISSUE THREAD

**Issue by sanderboom** [psifidotos/applet-window-buttons#71]
It seems that this applet is endlessly adding inotify watchers, eventually making the system unusable.

Recently, I ran into the problem of having a shortage of inotify watchers. E.g. running `journalctl -f` would return with 'Insufficient watch descriptors available. Reverting to -n.'.

I used [this script](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers) and identified many entries for `plasmashell`. I removed all panels, restarted plasmashell, started re-adding panels/applets back and `applet-window-buttons` immediately triggered 52 `plasmashell` inotify watchers.

Thanks for taking a look at this.

**Comment by psifidotos** [comment]
I can not reproduce in my system. 

1. Are you using latest master version?

I tried to reproduce in my system the following:
1. In my system there are NO Plasma panels
2. I added an EMPTY plasma panel
3. I added in [2] panel the window buttons appplet
4. I run in my system your script with: `./inotify.sh | grep plasmashell`
5. I get this result:

> 
> 
>       99    22300  /usr/bin/plasmashell
>        1    22300  /usr/bin/plasmashell
>        1    22300  /usr/bin/plasmashell
>        1    22300  /usr/bin/plasmashell
>        1    22300  /usr/bin/plasmashell
>        1    22300  /usr/bin/plasmashell
>        0    22300  /usr/bin/plasmashell

6. In my system the applet adds +3 inotify records which is normal.

**Comment by sanderboom** [comment]
> In my system the applet adds +3 inotify records which is normal.

Ok. Does this stay like this when you keep opening application windows (wild guess that this makes the nr increase). 

> Are you using latest master version?

I'm using `plasma5-applets-window-buttons 0.7.0-1` from [AUR](https://aur.archlinux.org/packages/plasma5-applets-window-buttons). I will test now with `plasma5-applets-window-buttons-git`. I will report back.

**Comment by sanderboom** [comment]
Same problem with `plasma5-applets-window-buttons-git`.

Right before I placed the applet:
```
λ cat ./20191219_201815.txt |grep plasmashell |wc -l
2
```

As we speak:

```
λ cat 20191219_203050.txt |grep plasmashell |wc -l
54
```

**Comment by psifidotos** [comment]
no Idea what is different in your system. The applet is using KDirWatch in order to track filesystem changes. If you can play with the lib code and checkout the issue case it would help.

**Comment by psifidotos** [comment]
@sanderboom I can confirm two cases that I found this is valid:

a) when the window buttons applet is opening its settings window +2 inotify trackers are added and never removed
b) when the window buttons applet is recreating its buttons e.g. when the buttons are changing sized then +1 inotify tracker is added and never removed...

I will track them down to check out what is happening...

**Comment by psifidotos** [comment]
@sanderboom you can retry if this improves things but my latest findings are that these trackers are added from the decoration and not from the applet. The applets needs to recreate the decoration in many cases and in such event the inotify(s) are accumulated without reducing or staying stable

**Comment by psifidotos** [comment]
@sanderboom please confirm that the situation is improved with this patch... new inotify(s) should be created now only when the decoration user option is changing.

**Comment by sanderboom** [comment]
Latest `plasma5-applets-window-buttons-git` gives me: 

Without widget:
```
λ cat 20191221_171502.txt |grep plasmashell |wc -l
2
```

After a while with widget (opening/closing settings window once):

```
λ cat 20191221_172327.txt |grep plasmashell |wc -l
8
```

After playing around with the settings:
```
λ cat 20191221_174036.txt |grep plasmashell |wc -l
12
```

Seems a lot less out of control! Cheers :raised_hands: 
Could it be that there are still some watchers that are never removed?

**Comment by psifidotos** [comment]
> Could it be that there are still some watchers that are never removed?

yep, every time a decoration is recreated an inotify is added... but that is not from the applet side as far as I have investigated it...

a decoration is created every time the settings window in opened or whenever the decoration used is changed for example from Breeze to Oxygen...

**Comment by sanderboom** [comment]
> yep, every time a decoration is recreated an inotify is added... but that is not from the applet side as far as I have investigated it...

I see. After restarting `plasmashell` the count is back at 4. Do you think this should be filed as an issue on plasma?

**Comment by psifidotos** [comment]
it would be better if we could locate first the code line that creates that inotify

**Comment by sanderboom** [comment]
Agreed. I'm not really familiar with the plasma/kde code, although I would want to be. 

BTW: is there a way to measure impact on performance by `window-buttons`, `window-title` and `window-appmenu`? My toppanel contains all of them (`window-title` even 2 instances).

**Comment by psifidotos** [comment]
meaning in cpu usage or memory?

**Comment by sanderboom** [comment]
> meaning in cpu usage or memory?

Yes, after the inotify watcher performance hit (when reaching the limit), I started wondering how we can measure applet performance anyway.
