### ISSUE TITLE
Consider kwin's closeable rule

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/applet-window-buttons#74]
Window decorations don't show the close button when the kwin rule `Closeable` in `Appearance and Fixes` is set to `No`. Not sure if possible or how difficult, but it would be great if this applet would do the same.

**Comment by psifidotos** [comment]
It is possible but it would require the following

1. For Latte it would need Latte to update its properties exposed for lastactivewindowand update also the windows tracked properties 
2. This applet to create new common window properties for Plasma and Latte trackers
3. Based on 2 this applet must respect its button visibility

So all in all I will leave it open and in case someone provides PRs all will review them for its step independelty

**Comment by kupiqu** [comment]
great, thank you!
