### ISSUE TITLE
Support plasma themes that use system colors 

### ISSUE THREAD

**Issue by d4em0n** [psifidotos/applet-window-buttons#75]
I tried to change theme and color, but icon still not showing. But i can still click the button.
![vokoscreen-2020-01-11_17-48-23](https://user-images.githubusercontent.com/29397847/72203150-c00e6c00-349a-11ea-96ca-2d4e681cda6a.gif)

**Comment by psifidotos** [comment]
Show me a screenshot of your applet settings

**Comment by psifidotos** [comment]
2. Plasma panel or Latte panel?

**Comment by d4em0n** [comment]
i can see window buttons while hovering them. this is plasma panel

![vokoscreen-2020-01-11_19-08-57](https://user-images.githubusercontent.com/29397847/72204001-dbcb3f80-34a5-11ea-9ce0-9f728bfd748d.gif)

![Screenshot_20200111_191106](https://user-images.githubusercontent.com/29397847/72204200-e686d400-34a7-11ea-9612-bdcef1ad4e5c.png)

**Comment by psifidotos** [comment]
1. What is your plasma theme?
2. What is the colors chosen at plasma system settings
3. Send the colors file chosen at plasma system settings

**Comment by d4em0n** [comment]
My plasma theme is default (breeze), colors is breeze. all my theme is default configuration from installation.
How to send the colors?
Sorry for a late reply

**Comment by psifidotos** [comment]
Ok makes sense, the applet is not ready for plasma themes that do not provide a color scheme file but rather use the system chosen color scheme.

As a workaround you can choose from applet settings, Colors: Breeze

**Comment by d4em0n** [comment]
i try to change all of colors in applet settings, including breeze, still not working

**Comment by psifidotos** [comment]
Show me a video when you change in applet settings, Decoration and Colors what is showing at the preview window buttons, you can use also Dropbox and Google drive for that.

**Comment by psifidotos** [comment]
btw if you change you plasma theme applied e.g. try Materia is not fixed? you have the same issue?

**Comment by psifidotos** [comment]
@d4em0n please reinstall the latest master version because I made a commit that might improve this for you.... make sure that after you install the applet, you will relogin at your plasma desktop. more precisely the commit is: https://github.com/psifidotos/applet-window-buttons/commit/e00358b336d3141249c5f65f6cec70a947d76510

**Comment by d4em0n** [comment]
it's working now, thanks

**Comment by d4em0n** [comment]
This issue exist in 5.18 @psifidotos

**Comment by psifidotos** [comment]
What issue of all described?

Plasma 5.18 opened too many issues for Latte and windows buttons, I don't know if I will manage to fix all of them.

**Comment by d4em0n** [comment]
ups sorry, just updated the repo in its works
