### ISSUE TITLE
Button order and selection reset on every latte launch

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/applet-window-buttons#77]
opensuse tumbleweed
latte-dock 0.9.7-1.1
applet-window-buttons 0.7.0-1.1

The configuration in `Default.layout.latte` never seems to change from:

```ini
[Containments][4][Applets][28][Configuration][General]
buttons=9|5|4|3|10|2
containmentType=Latte
visibility=ActiveMaximizedWindow
```

[video demo](https://streamable.com/amha2)

**Comment by psifidotos** [comment]
Go to your Latte Layouts and check that you haven't that layout to Locked/ReadOnly

**Comment by AndydeCleyre** [comment]
Yes, that was it, thank you!
