### ISSUE TITLE
No window buttons on dialog Windows

### ISSUE THREAD

**Issue by gilbertcutando** [psifidotos/applet-window-buttons#79]
If I maximize any dialog window I have no way to close, minimize or restore it. When the applet is configured to be always visible it only shows the parent window controls. 

Floating Dialog window focused (with "Show: Active window is maximized"):
![Screenshot_20200202_151744](https://user-images.githubusercontent.com/10154694/73609651-28e79080-45d0-11ea-896d-245ca9b0ece2.png)

Maximized dialog window focused (The applet doesn't show the buttons):
![Screenshot_20200202_151758](https://user-images.githubusercontent.com/10154694/73609655-31d86200-45d0-11ea-8794-5a7add9e506e.png)

**Comment by psifidotos** [comment]
This is not possible with plasma panels. For Latte v0.9.x is already supported.
