### ISSUE TITLE
Default settings make breeze (light) buttons hardly visible on (light) panel

### ISSUE THREAD

**Issue by bgouhier** [psifidotos/applet-window-buttons#8]
Using default settings (default Breeze theme), buttons appear as in breeze decorations i.e. bright as breeze title bars are dark.

However, breeze panels are light so buttons are barely visible. Maybe Color scheme should be taken from inactive colors where titlebar switch to light color??  

Buttons in panel:
![image](https://user-images.githubusercontent.com/7991370/48099976-c0213500-e221-11e8-846e-4eb985428666.png)

Buttons on breeze titlebar:
![image](https://user-images.githubusercontent.com/7991370/48100003-d929e600-e221-11e8-86d2-1af2699c1436.png)

Inactive breeze titlebar:
![image](https://user-images.githubusercontent.com/7991370/48100038-ffe81c80-e221-11e8-8010-d6217473ad43.png)

**Comment by psifidotos** [comment]
Best solution for this is #7 . You should also know that this is done automatically already when this is applet is added in a Latte panel of git version. After plasma 5.15 Latte will support a new painting one that will inform its applets how to paint themselves.

https://www.youtube.com/watch?v=QkPv0-tfsXk
