### ISSUE TITLE
Applet crashes Latte Layout

### ISSUE THREAD

**Issue by ryu-ketsueki** [psifidotos/applet-window-buttons#80]
This is actually to report two bugs. The first is the one mentioned in the title. Whenever I add this applet to a layout, it crashes latte. The second bug is a build error. I tried removing and reinstalling the applet and it gave me several errors:

`-- Found KF5: success (found suitable version "5.67.0", minimum required is "5.38.0") found components: CoreAddons Declarative Plasma PlasmaQuick 
-- KDECORATION2 VERSION MINOR : 18
-- Could not set up the appstream test. appstreamcli is missing.
-- Found KF5: success (found suitable version "5.67.0", minimum required is "5.26.0") found components: Plasma WindowSystem I18n Service ConfigWidgets 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ryuketsu/applet-window-buttons/build
[ 13%] Automatic MOC for target appletdecorationplugin
[ 13%] Built target appletdecorationplugin_autogen
[ 13%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o
/home/ryuketsu/applet-window-buttons/libappletdecoration/previewbridge.cpp: In member function ‘virtual std::unique_ptr<KDecoration2::DecoratedClientPrivate> Decoration::Applet::PreviewBridge::createClient(KDecoration2::DecoratedClient*, KDecoration2::Decoration*)’:
/home/ryuketsu/applet-window-buttons/libappletdecoration/previewbridge.cpp:75:83: error: invalid new-expression of abstract class type ‘Decoration::Applet::PreviewClient’
   75 |     auto ptr = std::unique_ptr<PreviewClient>(new PreviewClient(client, decoration));
      |                                                                                   ^
In file included from /home/ryuketsu/applet-window-buttons/libappletdecoration/previewbridge.cpp:27:
/home/ryuketsu/applet-window-buttons/libappletdecoration/previewclient.h:40:7: note:   because the following virtual functions are pure within ‘Decoration::Applet::PreviewClient’:
   40 | class PreviewClient : public QObject, public KDecoration2::ApplicationMenuEnabledDecoratedClientPrivate
      |       ^~~~~~~~~~~~~
In file included from /usr/include/KDecoration2/KDecoration2/Private/DecoratedClientPrivate:1,
                 from /home/ryuketsu/applet-window-buttons/libappletdecoration/previewclient.h:31,
                 from /home/ryuketsu/applet-window-buttons/libappletdecoration/previewbridge.cpp:27:
/usr/include/KDecoration2/kdecoration2/private/decoratedclientprivate.h:76:19: note:    ‘virtual QSize KDecoration2::DecoratedClientPrivate::size() const’
   76 |     virtual QSize size() const = 0;
      |                   ^~~~
/home/ryuketsu/applet-window-buttons/libappletdecoration/previewbridge.cpp: In member function ‘virtual std::unique_ptr<KDecoration2::DecorationSettingsPrivate> Decoration::Applet::PreviewBridge::settings(KDecoration2::DecorationSettings*)’:
/home/ryuketsu/applet-window-buttons/libappletdecoration/previewbridge.cpp:97:21: warning: redundant move in return statement [-Wredundant-move]
   97 |     return std::move(ptr);
      |            ~~~~~~~~~^~~~~
/home/ryuketsu/applet-window-buttons/libappletdecoration/previewbridge.cpp:97:21: note: remove ‘std::move’ call
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:193: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:151: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
`
All the required packages are installed. I'm using openSUSE Tumbleweed with KDE Unstable Repositories for testing. Updated all packages this morning.

**Comment by psifidotos** [comment]
The applet is not prepared for Plasma 5.18.It will take around a month in order to fix things for Plasma 5.18 except if you are a developer and you can provide  PR

**Comment by ryu-ketsueki** [comment]
I can't make heads nor tails with this. Sorry. Wish I could help. Thanks for the notice, though

**Comment by psifidotos** [comment]
duplicate #81
