### ISSUE TITLE
KDE Plasma 5.18 not work with applet 

### ISSUE THREAD

**Issue by damachine** [psifidotos/applet-window-buttons#81]
install log:

Vorbereitung...
Klone plasma5-applets-window-buttons Build-Dateien...
Überprüfe plasma5-applets-window-buttons Abhängigkeiten...
Warnung: plasma5-applets-window-buttons-0.8.0-1 ist aktuell -- Reinstalliere
Abhängigkeiten werden aufgelöst...
Interne Konflikte werden überprüft...

Erstelle plasma5-applets-window-buttons...
==> Erstelle Paket: plasma5-applets-window-buttons 0.8.0-1 (Di 11 Feb 2020 15:34:09 CET)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> Lade plasma5-applets-window-buttons-0.8.0.tar.gz herunter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   139    0   139    0     0    522      0 --:--:-- --:--:-- --:--:--   522

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 57562    0 57562    0     0  61629      0 --:--:-- --:--:-- --:--:--  127k
==> Überprüfe source Dateien mit sha256sums...
    plasma5-applets-window-buttons-0.8.0.tar.gz ... Durchgelaufen
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Entpacke plasma5-applets-window-buttons-0.8.0.tar.gz mit bsdtar
==> Beginne prepare()...
==> Beginne build()...
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/lib/ccache/bin/cc
-- Check for working C compiler: /usr/lib/ccache/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found KF5CoreAddons: /lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.67.0") 
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Found KF5Declarative: /lib64/cmake/KF5Declarative/KF5DeclarativeConfig.cmake (found version "5.67.0") 
-- Found KF5Plasma: /lib64/cmake/KF5Plasma/KF5PlasmaConfig.cmake (found version "5.67.0") 
-- Found KF5PlasmaQuick: /lib64/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake (found version "5.67.0") 
-- Found KF5: success (found suitable version "5.67.0", minimum required is "5.38.0") found components: CoreAddons Declarative Plasma PlasmaQuick 
-- KDECORATION2 VERSION MINOR : 18
-- Could not set up the appstream test. appstreamcli is missing.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5WindowSystem: /lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.67.0") 
-- Found Gettext: /bin/msgmerge (found version "0.20.1") 
-- Found KF5I18n: /lib64/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.67.0") 
-- Found KF5Service: /lib64/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.67.0") 
-- Found KF5ConfigWidgets: /lib64/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.67.0") 
-- Found KF5: success (found suitable version "5.67.0", minimum required is "5.26.0") found components: Plasma WindowSystem I18n Service ConfigWidgets 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/makepkg/plasma5-applets-window-buttons/src/build
make[1]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird betreten
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird betreten
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird betreten
Scanning dependencies of target appletdecorationplugin_autogen
Scanning dependencies of target org.kde.windowbuttons-plasmoids-metadata-json
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird verlassen
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird verlassen
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird betreten
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird betreten
[  9%] Generating org.kde.windowbuttons-plasmoids-metadata.json
[  9%] Automatic MOC for target appletdecorationplugin
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird verlassen
[  9%] Built target org.kde.windowbuttons-plasmoids-metadata-json
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird verlassen
[  9%] Built target appletdecorationplugin_autogen
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird betreten
Scanning dependencies of target appletdecorationplugin
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird verlassen
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird betreten
[ 13%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin_autogen/mocs_compilation.cpp.o
[ 18%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/buttonsmodel.cpp.o
[ 22%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/commontools.cpp.o
[ 27%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/auroraetheme.cpp.o
[ 31%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/appletdecorationplugin.cpp.o
[ 36%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/decorationpalette.cpp.o
[ 40%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/decorationsmodel.cpp.o
[ 45%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/environment.cpp.o
[ 50%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/padding.cpp.o
[ 54%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbutton.cpp.o
[ 59%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/decorationpalette.cpp: In Elementfunktion »void Decoration::Applet::DecorationPalette::update()«:
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/decorationpalette.cpp:139:103: Warnung: »QColor QColor::dark(int) const« ist veraltet: Use QColor::darker() instead [-Wdeprecated-declarations]
  139 |     m_inactiveForegroundColor = wmConfig.readEntry("inactiveForeground", m_activeForegroundColor.dark());
      |                                                                                                       ^
In Datei, eingebunden von /usr/include/qt/QtGui/qpalette.h:45,
                 von /usr/include/qt/QtGui/QPalette:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/decorationpalette.h:28,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/decorationpalette.cpp:23:
/usr/include/qt/QtGui/qcolor.h:235:30: Anmerkung: hier deklariert
  235 |     Q_REQUIRED_RESULT QColor dark(int f = 200) const noexcept;
      |                              ^~~~
[ 63%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewclient.cpp.o
[ 68%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewsettings.cpp.o
[ 72%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewshareddecoration.cpp.o
[ 77%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/schemecolors.cpp.o
[ 81%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/schemesmodel.cpp.o
[ 86%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/themeextended.cpp.o
[ 90%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/types.cpp.o
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewbridge.cpp: In Elementfunktion »virtual std::unique_ptr<KDecoration2::DecoratedClientPrivate> Decoration::Applet::PreviewBridge::createClient(KDecoration2::DecoratedClient*, KDecoration2::Decoration*)«:
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewbridge.cpp:75:83: Fehler: ungültiger new-Ausdruck für abstrakte Klasse »Decoration::Applet::PreviewClient«
   75 |     auto ptr = std::unique_ptr<PreviewClient>(new PreviewClient(client, decoration));
      |                                                                                   ^
In Datei, eingebunden von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewbridge.cpp:27:
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewclient.h:40:7: Anmerkung:   denn die folgenden virtuellen Funktionen sind rein innerhalb »Decoration::Applet::PreviewClient«:
   40 | class PreviewClient : public QObject, public KDecoration2::ApplicationMenuEnabledDecoratedClientPrivate
      |       ^~~~~~~~~~~~~
In Datei, eingebunden von /usr/include/KDecoration2/KDecoration2/Private/DecoratedClientPrivate:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewclient.h:31,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewbridge.cpp:27:
/usr/include/KDecoration2/kdecoration2/private/decoratedclientprivate.h:76:19: Anmerkung: 	»virtual QSize KDecoration2::DecoratedClientPrivate::size() const«
   76 |     virtual QSize size() const = 0;
      |                   ^~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewbridge.cpp: In Elementfunktion »virtual std::unique_ptr<KDecoration2::DecorationSettingsPrivate> Decoration::Applet::PreviewBridge::settings(KDecoration2::DecorationSettings*)«:
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewbridge.cpp:97:21: Warnung: redundantes Verschieben in Rückgabeanweisung [-Wredundant-move]
   97 |     return std::move(ptr);
      |            ~~~~~~~~~^~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewbridge.cpp:97:21: Anmerkung: entfernen Sie den Aufruf von »std::move«
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:193: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewclient.cpp: In Elementfunktion »virtual void Decoration::Applet::PreviewClient::requestShowToolTip(const QString&)«:
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/previewclient.cpp:388:55: Warnung: unverwendeter Parameter »text« [-Wunused-parameter]
  388 | void PreviewClient::requestShowToolTip(const QString &text)
      |                                        ~~~~~~~~~~~~~~~^~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp: In Elementfunktion »virtual void Decoration::Applet::AppletDecorationPlugin::registerTypes(const char*)«:
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:60:50: Warnung: »int qmlRegisterType() [mit T = Decoration::Applet::Padding]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   60 |     qmlRegisterType<Decoration::Applet::Padding>();
      |                                                  ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:60:50: Warnung: »int qmlRegisterType() [mit T = Decoration::Applet::Padding]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   60 |     qmlRegisterType<Decoration::Applet::Padding>();
      |                                                  ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:61:56: Warnung: »int qmlRegisterType() [mit T = Decoration::Applet::PreviewClient]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   61 |     qmlRegisterType<Decoration::Applet::PreviewClient>();
      |                                                        ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:61:56: Warnung: »int qmlRegisterType() [mit T = Decoration::Applet::PreviewClient]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   61 |     qmlRegisterType<Decoration::Applet::PreviewClient>();
      |                                                        ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:62:56: Warnung: »int qmlRegisterType() [mit T = Decoration::Applet::PreviewBridge]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   62 |     qmlRegisterType<Decoration::Applet::PreviewBridge>();
      |                                                        ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:62:56: Warnung: »int qmlRegisterType() [mit T = Decoration::Applet::PreviewBridge]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   62 |     qmlRegisterType<Decoration::Applet::PreviewBridge>();
      |                                                        ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:63:47: Warnung: »int qmlRegisterType() [mit T = KDecoration2::Decoration]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   63 |     qmlRegisterType<KDecoration2::Decoration>();
      |                                               ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
/tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:63:47: Warnung: »int qmlRegisterType() [mit T = KDecoration2::Decoration]« ist veraltet: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   63 |     qmlRegisterType<KDecoration2::Decoration>();
      |                                               ^
In Datei, eingebunden von /usr/include/qt/QtQml/qqmlengine.h:47,
                 von /usr/include/qt/QtQml/QQmlEngine:1,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/environment.h:25,
                 von /tmp/makepkg/plasma5-applets-window-buttons/src/applet-window-buttons-0.8.0/libappletdecoration/appletdecorationplugin.cpp:24:
/usr/include/qt/QtQml/qqml.h:138:74: Anmerkung: hier deklariert
  138 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
make[2]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:462: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Fehler 2
make[1]: Verzeichnis „/tmp/makepkg/plasma5-applets-window-buttons/src/build“ wird verlassen
make: *** [Makefile:141: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

**Comment by Seqularise** [comment]
plasma 5.18, qt 5.14.1,  git package from aur
```
[ 45%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/environment.cpp.o
[ 50%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/padding.cpp.o
[ 54%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbutton.cpp.o
[ 59%] Building CXX object libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o
/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewbridge.cpp: In member function 'virtual std::unique_ptr<KDecoration2::DecoratedClientPrivate> Decoration::Applet::PreviewBridge::createClient(KDecoration2::DecoratedClient*, KDecoration2::Decoration*)':
/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewbridge.cpp:75:83: error: invalid new-expression of abstract class type 'Decoration::Applet::PreviewClient'
   75 |     auto ptr = std::unique_ptr<PreviewClient>(new PreviewClient(client, decoration));
      |                                                                                   ^
In file included from /home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewbridge.cpp:27:
/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewclient.h:40:7: note:   because the following virtual functions are pure within 'Decoration::Applet::PreviewClient':
   40 | class PreviewClient : public QObject, public KDecoration2::ApplicationMenuEnabledDecoratedClientPrivate
      |       ^~~~~~~~~~~~~
In file included from /usr/include/KDecoration2/KDecoration2/Private/DecoratedClientPrivate:1,
                 from /home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewclient.h:31,
                 from /home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewbridge.cpp:27:
/usr/include/KDecoration2/kdecoration2/private/decoratedclientprivate.h:76:19: note:    'virtual QSize KDecoration2::DecoratedClientPrivate::size() const'
   76 |     virtual QSize size() const = 0;
      |                   ^~~~
/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewbridge.cpp: In member function 'virtual std::unique_ptr<KDecoration2::DecorationSettingsPrivate> Decoration::Applet::PreviewBridge::settings(KDecoration2::DecorationSettings*)':
/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewbridge.cpp:97:21: warning: redundant move in return statement [-Wredundant-move]
   97 |     return std::move(ptr);
      |            ~~~~~~~~~^~~~~
/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/applet-window-buttons/libappletdecoration/previewbridge.cpp:97:21: note: remove 'std::move' call
make[2]: *** [libappletdecoration/CMakeFiles/appletdecorationplugin.dir/build.make:193: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/previewbridge.cpp.o] Error 1
make[2]: Leaving directory '/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:462: libappletdecoration/CMakeFiles/appletdecorationplugin.dir/all] Error 2
make[1]: Leaving directory '/home/seqularise/.cache/yay/plasma5-applets-window-buttons-git/src/build'
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in package().
    Aborting...
Error making: plasma5-applets-window-buttons-git

```

**Comment by kupiqu** [comment]
This is also related to this:

https://bugs.kde.org/show_bug.cgi?id=417434

**Comment by psifidotos** [comment]
fixed with https://github.com/psifidotos/applet-window-buttons/commit/6d6c54467b1778317b759e410f05cdccef8fda94
