### ISSUE TITLE
Plasma 5.17.5 - Always visible doesn't work anymore 

### ISSUE THREAD

**Issue by ciolansteen** [psifidotos/applet-window-buttons#83]
Having a window open make window buttons appear
![1](https://user-images.githubusercontent.com/8395752/74322683-f8041a00-4d8c-11ea-8bf8-92627215ba20.png)

Closing window causes buttons to diss\appear 
![2](https://user-images.githubusercontent.com/8395752/74322727-0ce0ad80-4d8d-11ea-8ea0-6955ffce4cee.png)

![3](https://user-images.githubusercontent.com/8395752/74322743-14a05200-4d8d-11ea-8e74-e3783d669982.png)

**Comment by psifidotos** [comment]
As long as there is no other window this is normal and intentional

**Comment by ciolansteen** [comment]
The option "At least one window is shown" makes no sense anymore in this case. In the old version, when there was no window open the buttons were still present but inactive. In ver 0.7.0-1 this feature works as expected.
