### ISSUE TITLE
Buttons aren't shown in plasma 5.18 

### ISSUE THREAD

**Issue by quarckster** [psifidotos/applet-window-buttons#86]
Buttons aren't shown in widget config and on panel. Adjusting "Decoration" and "Colors" fields doesn't make any difference.

applet-window-buttons:  v0.8.1
plasma: 5.18

![Screenshot_20200214_220001](https://user-images.githubusercontent.com/1011257/74567321-cef2ad80-4f75-11ea-933a-0106c7177395.png)

**Comment by psifidotos** [comment]
You need to rebuild and reinstall
