### ISSUE TITLE
[Enhancement] Allow an easy way to uninstall if it was installed from source

### ISSUE THREAD

**Issue by cfviotti** [psifidotos/applet-window-buttons#87]
I see now that there is a PPA available for Ubuntu distros, and I'd wish to remove my current installation made from source in order to rely on the PPA, since I may get automatic updates now!

There is no `make uninstall` rule currently, and I'm not familiar with what the install rule actually did to undo the steps manually. It would be great to have that available! 
Thank you!

**Comment by rodrigopedra** [comment]
If you installed using the method described in the README, the make process might have generated a `install_manifest.txt` file which lists all the generated files.

Just remove all the files listed inside it and you should be fine.

I guess it might be a good idea to regenerate the plasma indices using this:

~~~bash
$ plasmapkg2 -g --generate-index
~~~

But that might not be needed.

One more thing: tried googling for the PPA but could not find anything about it. Mind to post the link?

**Comment by cfviotti** [comment]
Thanks! I'll give it try later!
As for the PPA, it's a bit hidden in the repo itself! Check the [INSTALLATION.md](https://github.com/psifidotos/applet-window-buttons/blob/master/INSTALLATION.md) :wink:

**Comment by rodrigopedra** [comment]
Thanks for the heads up! Missed that somehow
