### ISSUE TITLE
applet broken again on 5.18

### ISSUE THREAD

**Issue by zany130** [psifidotos/applet-window-buttons#90]
have a look here I provided a backtrace https://bugs.kde.org/show_bug.cgi?id=418766#c5

I installed from the aur so i should be using the latest version

**Comment by psifidotos** [comment]
AUR is not accurate... Try to rebuild install manually.

**Comment by zany130** [comment]
just did still have the same issue

**Comment by psifidotos** [comment]
no idea then...
it works perfectly in my opensuse system

**Comment by zany130** [comment]
its that I'm not even sure its a bug with the applet I'm still convinced its with latte dock as the latest version of the applet was working BEFORE I updated to latte dock 0.9.9

**Comment by psifidotos** [comment]
Latte is not using KDEcoration 2 library from which this crash is from.

Have you tried to change the theme used by the window buttons applet? There is a chance that the problem is from the decoration you are using, have you tried with Breeze buttons?

**Comment by zany130** [comment]
that could make a difference? ill try

**Comment by psifidotos** [comment]
Buttons are not drawn from the applet, they are are drawn directly from their own implementation.

**Comment by zany130** [comment]
yup i think that was it i tried changing it back to brezze and it hasn't crashed yet for refrence i was using the buttons from this theme https://github.com/n4n0GH/hello

**Comment by zany130** [comment]
but the weird thing is I have that theme set for my desktop and it doesn't crash that
