### ISSUE TITLE
Window buttons cant display button

### ISSUE THREAD

**Issue by denzveloper** [psifidotos/applet-window-buttons#91]
I'm installing "applet-window-buttons" with AUR repo (https://aur.archlinux.org/packages/plasma5-applets-window-buttons-git/) and success. but when i drag it into panel and it just show icon not  a button window and when i click it says:

> plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: plugin cannot be loaded for module "org.kde.appletdecoration": Cannot load library /usr/lib/qt/qml/org/kde/appletdecoration/libappletdecorationplugin.so: (libkdecorations2private.so.6: cannot open shared object file: No such file or directory)

Screenshoot: https://imgur.com/gallery/6Lv2viV
Video: https://imgur.com/gallery/aWNWUGO

OS: Manjaro Linux (KDE Plasma 5.18)
Version 19.0.2

**Comment by magiruuvelvet** [comment]
Did you restart your plasmashell (`plasmashell --restart`). This applet, as the error says, has a native C++ extension and you need to restart plasmashell for the plugin to pick up. Also make sure the file actually exists and was installed at that location.

**Comment by denzveloper** [comment]
Ok, it work again. thanks!
