### ISSUE TITLE
Broken After Latest Manjaro Update

### ISSUE THREAD

**Issue by TomerAberbach** [psifidotos/applet-window-buttons#92]
I updated to the latest version of Manjaro today and the applet no longer works correctly. The buttons stay hidden when a window is maximized. Additionally, it may accidentally be using a lot of resources because `/usr/bin/plasmashell` was using 100% CPU until I removed the widget from my desktop.

Let me know if you need any other information. Thanks in advance!

Manjaro:  19.0.2
KDE: 5.18.3

**Comment by psifidotos** [comment]
works perfectly in my system, so I suppose the Arch/Manjaro package is again broken... It probably needs to be rebuilt when current distro provided plasma/kde libraries...

Try to build manually and install it... and check out if the issues are still valid...

**Comment by laszlobarnabas** [comment]
I updated my Manjaro yesterday, and instead of the applet, I got this message:
> Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: plugin cannot be loaded for module "org.kde.appletdecoration": Cannot load library /usr/lib/qt/qml/org/kde/appletdecoration/libappletdecorationplugin.so: (libkdecorations2private.so.6: cannot open shared object file: No such file or directory)

the same Plasma version: 5.18.3
KDecoration version: 5.18.3-1

**Comment by psifidotos** [comment]
Try to build manually and install it... and check out if the issues are still valid...

**Comment by laszlobarnabas** [comment]
After installing the latest build, it works fine again. Thanks! I don't know why I didn't tried it first.

**Comment by TomerAberbach** [comment]
I did the same and now it works! Should I close the issue?

**Comment by psifidotos** [comment]
You can also report this to arch manjaro packagers

**Comment by rogerguti** [comment]
I am sorry to re-write here, but I cannot fix it myself. The problem happened around the same time as the original message, and I have the same packages as laszlobarnabas.
I tried installing and re-installing from the AUR and from the latest master here directly, waiting for a package update from Manjaro, etc. and the error persists.

I am quite the beginner with all this, so I would appreciate the help if possible. Should I paste the output of the build & installation process? There seem to be some warnings but in the end the process finishes successfully (I think). Thanks!

**Comment by trmdi** [comment]
@rogerguti if you are new to Linux, try openSUSE Tumbleweed, it's much more stable than Manjaro/Arch.

**Comment by rogerguti** [comment]
@trmdl Thanks! I have been using different distros and desktops for some years already, even Manjaro for a couple. I have been able to solve the problems that came out eventually, this is the first one where I have tried many times without a solution. What I meant is that I am a beginner with the building process.
