### ISSUE TITLE
Add new hiding option: Do not hide when any window is maximized

### ISSUE THREAD

**Issue by 4VRDriver** [psifidotos/applet-window-buttons#93]
Hello,
it would be a nice feature to just hide the window button if there is no window maximized at all. The current option hides the button, when the maximized window is not longer active. But this causes confusion in my opinion. If I open a menu from the control bar for example, the buttons disappear and slide the just clicked button away from the cursor.

**Comment by psifidotos** [comment]
But that would require that the window buttons should also interact with the maximized window and not the active one when there is a maximized window shown.

**Comment by 4VRDriver** [comment]
You're right, I didn't think about that.

**Comment by psifidotos** [comment]
in general all the Window Applet(s) should be adjusted accordingly for the use case... Meaning Window Title, Button, AppMenu

**Comment by psifidotos** [comment]
no idea what you are describing

**Comment by pmartycz** [comment]
https://streamable.com/747t4

When opening Application Menu is shown Window Buttons disappear and Window Title changes to "Default" while Global Menu continues to show application menu items as expected.

**Comment by psifidotos** [comment]
for Window Buttons you can set: At least one window is shown
for Window AppMenu I have no idea if this is possible, it should...

**Comment by psifidotos** [comment]
Window Buttons already provide an option called: At least one window is shown.

**Comment by psifidotos** [comment]
in any case... no time any more... too many projects etc. etc. and NOONE is contributing or helping... so enjoy what you get because I dont know if improvements or additions will be added in the future.
