### ISSUE TITLE
Error Loading QML File

### ISSUE THREAD

**Issue by erayerdin** [psifidotos/applet-window-buttons#96]
I'm on Manjaro KDE. The applet cannot load qml, saying below on click:

```
Error loading QML file: file:///usr/share/plasma/plasmoids/org.kde.windowbuttons/contents/ui/main.qml:26:1: plugin cannot be loaded for module "org.kde.appletdecoration": Cannot load library /usr/lib/qt/qml/org/kde/appletdecoration/libappletdecorationplugin.so: (libkdecorations2private.so.6: cannot open shared object file: No such file or directory)
```

Will troubleshoot and write what I will come up with.

***

# Environment

 - Manjaro KDE 19.0.2
 - plasmashell 5.18.3

**Comment by psifidotos** [comment]
classic Manjaro issue...
have you built / install the applet by yourself  or you used the prepackaged version of Arch/Manjaro?

**Comment by erayerdin** [comment]
# Troubleshooting

## libkdecorations2private.so.6

Looks like my system does not have `/usr/lib/libkdecorations2private.so.6`, instead it has 5.18.3 and 7. I will find it somewhere.

**Comment by erayerdin** [comment]
> classic Manjaro issue...
> have you built / install the applet by yourself or you used the prepackaged version of Arch/Manjaro?

I have built it myself. Actually let me have a look if it has an AUR entry.

**Comment by xMase** [comment]
arojas the maintainer of the repository on arch did not want to hear reason to add the correct path for manjaro (probably for laziness) so having the problem I folded back to use the git package that presents the path fix ([git repo aur)](https://aur.archlinux.org/packages/plasma5-applets-window-buttons-git/)

**Comment by psifidotos** [comment]
`the fix is to add this` -DCMAKE_INSTALL_PREFIX=/usr` on cmake `

this is distro responsibility

**Comment by psifidotos** [comment]
file: https://github.com/psifidotos/applet-window-buttons/blob/master/install.sh

contains the mentioned line but if a distro want different paths then the distro should adjust that on distro level

**Comment by psifidotos** [comment]
upstream

**Comment by xMase** [comment]
> 
> 
> `the fix is to add this -DCMAKE_INSTALL_PREFIX=/usr on cmake `
> 
> this is distro responsibility



> 
> 
> file: https://github.com/psifidotos/applet-window-buttons/blob/master/install.sh
> 
> contains the mentioned line but if a distro want different paths then the distro should adjust that on distro level

this is true but [here](https://wiki.archlinux.org/index.php/KDE_package_guidelines):
![Wgr1Q7T](https://user-images.githubusercontent.com/11925311/77849454-fae78c80-71cb-11ea-9b81-f0086a3cc215.png)
and the current aur package override your installation file and use a cmake without the parameter [(look here)](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-window-buttons)

**Comment by psifidotos** [comment]
> and the current aur package override your installation file and use a cmake without the parameter [(look here)](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-window-buttons)

the AUR package does not follow the AUR KDE guidelines... so this is the AUR package fault.
