### ISSUE TITLE
How can I install in Manjaro?

### ISSUE THREAD

**Issue by SoyDiego** [psifidotos/applet-window-buttons#98]
I'm trying with ./install.sh but i receive this error:

>  diego@diego-pc  ~/Escritorio/theme/applet-window-buttons-0.8.1  ./install.sh
> CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
>   The package name passed to `find_package_handle_standard_args`
>   (KF5CoreAddons) does not match the name of the calling package (KF5).  This
>   can lead to problems in calling code that expects `find_package` result
>   variables (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
>   /usr/local/share/ECM/find-modules/FindKF5.cmake:78 (find_package_handle_standard_args)
>   CMakeLists.txt:18 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
>   The package name passed to `find_package_handle_standard_args`
>   (KF5Declarative) does not match the name of the calling package (KF5).
>   This can lead to problems in calling code that expects `find_package`
>   result variables (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
>   /usr/local/share/ECM/find-modules/FindKF5.cmake:78 (find_package_handle_standard_args)
>   CMakeLists.txt:18 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
>   The package name passed to `find_package_handle_standard_args` (KF5Plasma)
>   does not match the name of the calling package (KF5).  This can lead to
>   problems in calling code that expects `find_package` result variables
>   (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
>   /usr/local/share/ECM/find-modules/FindKF5.cmake:78 (find_package_handle_standard_args)
>   CMakeLists.txt:18 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Error at /usr/local/share/ECM/cmake/ECMConfig.cmake:11 (message):
>   File or directory /usr/local/include/KF5 referenced by variable
>   PlasmaQuick_INCLUDE_DIR does not exist !
> Call Stack (most recent call first):
>   /usr/lib64/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake:45 (set_and_check)
>   /usr/local/share/ECM/find-modules/FindKF5.cmake:74 (find_package)
>   CMakeLists.txt:18 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/diego/Escritorio/theme/applet-window-buttons-0.8.1/build/CMakeFiles/CMakeOutput.log".
> make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.

Thanks

**Comment by psifidotos** [comment]
You need to ask manjaro community
