### ISSUE TITLE
Option to slide the buttons

### ISSUE THREAD

**Issue by moshpirit** [psifidotos/applet-window-buttons#99]
One of the features I liked the most from the previous applet was the option of hiding the buttons and just show them when the mouse was there, is there any way to make it come back again?

Thank you so much for your hard work!

**Comment by psifidotos** [comment]
Show me a video of your suggested behavior

**Comment by moshpirit** [comment]
Hmm I thought the `Active Window Control` applet ([GitHub](https://github.com/kotelnik/plasma-applet-active-window-control) moved [here](https://phabricator.kde.org/source/plasma-active-window-control/)]) was made by you too, sorry. [This is what I meant though](https://i.imgur.com/OoF3lX9.mp4)

**Comment by psifidotos** [comment]
This is possible to add but only with Latte panels

**Comment by moshpirit** [comment]
Do you mean on Latte panels/docks or if Latte is installed? I have Latte installed but I'm not using it (not even for the recording) but I guess the build structure is probably different from what AWC uses

**Comment by psifidotos** [comment]
I mean on Latte panels. In order for this to work it would need window title applet to communicate the window buttons applet. For plasma panels this is only achievable on applet level and it's should create on its own such mechanism. On the other hand Latte takes responsibility for this and provides an api for qml applets to contact other qml applets.

**Comment by moshpirit** [comment]
Oh, I see, but would it be possible to adjust the space used by the icons? I mean instead of using a fixed space and telling the other applets "hey, use my space" just use an adjustable space and so when it hides the buttons it leaves this space free (like when the global menu or the name of the program uses more or less space depending on the program with the space in the right side and the space separator).

Again, I'm no developer, so probably this is not possible at all and I'm causing the death of so many neurons right now, so I apologize for that.

**Comment by psifidotos** [comment]
The behavior will be exactly like your video, that is of no concern. Such behavior is already provided for Window Title and Window AppMenu. These applets when used inside a Latte panel they provide options in order to work in Unity mode. It means that the AppMenu is shown only when the mouse hovers the Window Title.
